version: '3'
services:
  redis:
      image: redis:latest
      container_name: stress-testing-redis
      ports:
          - '6379:6379'
  leader-node:
    build:
      context: ../../
      dockerfile: ./servers/load-testing/Dockerfile
    ports:
      - "5001:80"
    environment:
      - MODE=leader
      - NUM_TOWNS=10
      - NUM_CHANNELS_PER_TOWN=10
      - NUM_FOLLOWERS=2
      # TODO: generate random private key
      - RIVER_NODE_URL=http://localhost:5157
      - BASE_CHAIN_RPC_URL=http://localhost:8545
      - CHANNEL_SAMPLING_RATE=100
      # 10 minutes
      - LOAD_TEST_DURATION_MS=600000
      - COORDINATOR_LEAVE_CHANNELS=true
    depends_on:
      - redis
  follower-1:
    build:
      context: ../../
      dockerfile: ./servers/load-testing/Dockerfile
    ports:
      - "5002:80"
    environment:
      - MODE=follower
      - RIVER_NODE_URL=http://localhost:5157
      - BASE_CHAIN_RPC_URL=http://localhost:8545
      # 10 minutes
      - LOAD_TEST_DURATION_MS=600000
      - MAX_MSG_DELAY_MS=10000
      - JOIN_FACTOR=2
    depends_on:
      - redis
  follower-2:
    build:
      context: ../../
      dockerfile: ./servers/load-testing/Dockerfile
    ports:
      - "5003:80"
    environment:
      - MODE=follower
      - RIVER_NODE_URL=http://localhost:5157
      - BASE_CHAIN_RPC_URL=http://localhost:8545
      # 10 minutes
      - LOAD_TEST_DURATION_MS=600000
      - MAX_MSG_DELAY_MS=10000
      - JOIN_FACTOR=2
    depends_on:
      - redis
