service: zion-unfurl
frameworkVersion: '3'

provider:
    name: aws
    runtime: nodejs16.x

functions:
    unfurl:
        handler: handlers/unfurl/handler.unfurl
        environment: ${file(env.json)}
        url:
            # https://www.serverless.com/framework/docs/providers/aws/guide/functions
            cors:
                allowedOrigins:
                    - http://localhost:3000
                    - http://localhost:3001
                    - https://harmony-web.onrender.com # will need to check this works
                allowCredentials: true

        events:
            - httpApi:
                  path: /
                  method: get

plugins:
    - serverless-plugin-typescript
    - serverless-offline
