homeserver:
  # The domain name of your homeserver
  #
  server_name: localhost

  # The URL for connecting to your homeserver
  #
  url: http://localhost:8008

  # Optional. Used to specify the port of the appservice in the config, rather than the command line.
  # This will be overriden by any ports given in the process arguments.
  #
  #appservice_port: 6868

  # Optional. Used to specify the host to listen on for the appservice.
  # appservice_host: 0.0.0.0

# The prefix to give Ethereum users on the Matrix server
#
username_prefix: "ethereum_"
# Optional. Use a matrix room to issue commands to the bridge
#
# matrix_admin_room: "!aBcDeF:matrix.org"

# Optional
# logging:
#   console: "info" # One of "debug", "info", "warning", "error", "silent"

#   # Files that the bridge may log into. The key is the minimum level to report.
#   #
#   files:
#       "./debug.log": "info"
#       "./error.log": "error"
