main = "./src/index.ts"
name = "token-worker"
compatibility_date = "2023-01-18"
account_id="9840f8a36a817b103e00e29a0e2bad6f"
minify=true
node_compat=true

[dev]
ip = "localhost"
port = 8006
local_protocol = "http"

[vars]
# VAR_NAME = "some_value"
ENVIRONMENT = "development"


# The necessary secrets are: 
# ALCHEMY_API_KEY
# INFURA_API_KEY
# INFURA_API_SECRET
# AUTH_SECRET 
# for local development, you can add these in .dev.vars
# 
# For production, you can add these in the Cloudflare dashboard or run
# `echo <VALUE> | wrangler secret put <NAME>` for each of these

# production routes
# yarn publish:prod
[env.production]
routes = [{ pattern = "token-worker.towns.com", custom_domain = true }]
vars = { ENVIRONMENT = "production" }

# test routes
# yarn publish:test
[env.test]
routes = [{ pattern = "token-worker-test.towns.com", custom_domain = true }]
vars = { ENVIRONMENT = "test" }
