# Blockchain configuration
baseChain:
    chainId: 84532
    networkUrl: 'https://nexus-rpc-worker-test-beta.towns.com/84532?key=NOT_SET'
riverChain:
    chainId: 6524490
    networkUrl: 'https://devnet.rpc.river.build'

# Base contracts
architectContract:
    address: '0x877Cd3076d8Bd6C2fBaA60ceFBe41Ddb1C9DC24A'
walletLinkContract:
    address: '0x4B53e313773df56d8f8b96942c5Cf7a49cFc9774'

# River contracts
registryContract:
    address: '0xEE75eC5501d9952Dc5F380b34e89F4A3f9E88327'
