# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: 'en-US'
tone_instructions: 'Be very concise and to the point'
early_access: true
enable_free_tier: true
reviews:
    profile: 'chill'
    request_changes_workflow: false
    high_level_summary: false
    review_status: false
    poem: false
    collapse_walkthrough: true
    sequence_diagrams: false
    path_filters:
        - '!packages/generated/**'
        - '!packages/proto/src/gen/**'
        - '!packages/proto/src/protocol_*.ts'
        - '!packages/subgraph/generated/**'
        - '!packages/contracts/out/**'
        - '!packages/contracts/deployments/**'
        - '!packages/contracts/broadcast/**'
        - '!packages/contracts/typings/**'
        - '!core/**/gen/**'
        - '!**/dist/**'
        - '!**/coverage/**'
        - '!**/.turbo/**'
        - '!package.json'
        - '!bun.lock'
        - '!go.work.sum'
        - '!go.sum'
    auto_review:
        enabled: true
        drafts: false
chat:
    auto_reply: true
