checksumBehavior: throw

compressionLevel: mixed

enableGlobalCache: true

enableImmutableCache: false

enableImmutableInstalls: true

enableTelemetry: false

nmMode: hardlinks-global

nodeLinker: node-modules

plugins:
    - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
      spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.8.0.cjs
