checksumBehavior: throw

compressionLevel: 0

enableGlobalCache: true

enableImmutableCache: false

enableTelemetry: false

nmMode: hardlinks-global

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.9.1.cjs
