[profile.default]
solc = "0.8.17"
libs = ["node_modules", "lib"]
verbosity = 3
fs_permissions = [{ access = "write", path = "./packages"}, { access = "write", path = "./servers/dendrite"}]
extra_output_files = ["metadata", "abi"]
gas_reports = ["*"]
optimizer = true
optimizer_runs = 1000000

[rpc_endpoints]
goerli = "https://eth-goerli.g.alchemy.com/v2/Sc1gVeBmMXEGDgS6_mMP-gbewns4h1EN"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
