[profile.default]
solc = "0.8.19"
src = "packages/contracts"
test = "packages/contracts/test"
out = "packages/contracts/out"
cache_path = "packages/contracts/cache"
libs = ["node_modules", "lib"]
verbosity = 3
fs_permissions = [{ access = "read-write", path = "./packages"}, { access = "read-write", path = "./servers/dendrite"}, { access = "read-write", path = "./casablanca/node/auth"}]
gas_reports = ["*"]
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
