[profile.default]
solc = "0.8.16"
libs = ["node_modules", "lib"]
verbosity = 3
fs_permissions = [{ access = "write", path = "./packages"}]
extra_output_files = ["metadata", "abi"]
gas_reports = ["*"]
optimizer = true
optimizer_runs = 20000

[profile.governance]
src = 'contracts/zion-governance/src'
test = 'contracts/zion-governance/test'
out = 'contracts/zion-governance/out'
broadcast = "contracts/zion-governance/broadcast"
gas_reports = ["CouncilNFT", "ZionSpaceManager"]
ffi = true

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
