[profile.default]
solc = "0.8.16"
libs = ["node_modules", "lib"]
verbosity = 3
fs_permissions = [{ access = "write", path = "./packages"}]
extra_output_files = ["metadata", "abi"]

[profile.governance]
src = 'contracts/zion-governance/contracts'
test = 'contracts/zion-governance/test/'
out = 'contracts/zion-governance/artifacts_foundry'
broadcast = "contracts/zion-governance/broadcast"
gas_reports = ["CouncilNFT", "ZionSpaceManager"]
ffi = true

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
