[profile.default]
# Compiler settings
auto_detect_solc = false # Foundry will automatically try to resolve appropriate Solidity compiler versions
solc_version = "0.8.29" # Uses a single Solidity compiler version for the project
evm_version = "cancun" # The EVM version to use during tests.
via_ir = false # Whether to use the Solidity intermediate representation.
optimizer = true # Whether to enable the Solidity optimizer.
optimizer_runs = 4294967295 # The amount of optimizer runs to perform.
bytecode_hash = "none" # Determines the hash method for the metadata hash that is appended to the bytecode
cbor_metadata = false # Remove all metadata hashes from your contract's bytecode.
libs = ["node_modules"]
out = "contracts/out" # The path to put contract artifacts in, relative to the root of the project.
script = "contracts/scripts" # The path to the contract scripts relative to the root of the project.
src = "contracts" # The path to the contract sources relative to the root of the project.
test = "contracts/test" # The path to the test contract sources relative to the root of the project.
extra_output = ["abi", "bin"]
extra_output_files = ["abi", "bin"]

# Test settings
fuzz = { runs = 256 } # The amount of fuzz runs to perform for each fuzz test case.
cache_path = "contracts/cache" # The path to the cache, relative to the root of the project.
block_timestamp = 1_680_220_800 # The value of block.timestamp in tests. March 31, 2023 at 00:00 GMT
verbosity = 3 # The verbosity level to use during tests.
ffi = true
fs_permissions = [
  { access = "read-write", path = "./contracts/deployments" },
  { access = "read-write", path = "./contracts/in" },
  { access = "read", path = "./scripts/bytecode-diff/source-diffs" },
] # Configures permissions for cheatcodes that touch the filesystem
gas_reports = ["*"] # The contracts to print gas reports for.

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
base = "${BASE_RPC_URL}"
base_anvil = "${BASE_ANVIL_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
river = "${RIVER_RPC_URL}"
river_anvil = "${RIVER_ANVIL_RPC_URL}"
river_devnet = "${RIVER_DEVNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

[fmt]
line_length = 80
tab_width = 2
bracket_spacing = true
int_types = "long"
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
wrap_comments = false

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
