version: '3.8'
name: towns
services:
    subgraph-db:
        image: postgres:16.1-alpine
        restart: always
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres']
            interval: 10s
            timeout: 5s
            retries: 5
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=ponder
        ports:
            - '5432:5432'
        volumes:
            - subgraph-db:/var/lib/postgresql/data

    subgraph:
        build:
            context: ../../
            dockerfile: packages/subgraph/Dockerfile
        depends_on:
            subgraph-db:
                condition: service_healthy
        env_file:
            - .env.gamma
        environment:
            - NODE_ENV=production
            - DATABASE_SCHEMA=public
            - DATABASE_URL=postgresql://postgres:postgres@subgraph-db:5432/ponder
        ports:
            - '42069:42069'

volumes:
    subgraph-db:
        driver: local
