export const TownsTokenConfig = {
    sizes: {
        xxs: {
            containerSize: 60,
            addressSize: 36,
            addressRadius: 6,
            badgeSize: 36,
            badgeRadius: 2,
            fontSize: 4,
            maxTextHeight: 10,
            borderRadius: 'xs',
        },
        sm: {
            containerSize: 130,
            addressSize: 105,
            addressRadius: 20,
            badgeSize: 85,
            badgeRadius: 16,
            fontSize: 8,
            maxTextHeight: 42,
            borderRadius: 'md',
        },
        md: {
            containerSize: 150,
            addressSize: 135,
            addressRadius: 10,
            badgeSize: 108,
            badgeRadius: 14,
            fontSize: 8,
            maxTextHeight: 80,
            borderRadius: 'md',
        },
        lg: {
            containerSize: 200,
            addressSize: 190,
            addressRadius: 20,
            badgeSize: 160,
            badgeRadius: 16,
            fontSize: 12,
            maxTextHeight: 80,
            borderRadius: 'md',
        },
        xl: {
            containerSize: 270,
            addressSize: 270,
            addressRadius: 32,
            badgeSize: 216,
            badgeRadius: 16,
            fontSize: 15,
            maxTextHeight: 120,
            borderRadius: 'md',
        },
    },
} as const

export type TownsTokenSize = keyof typeof TownsTokenConfig.sizes
