// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: internode.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewEventReceivedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Event *Envelope `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	// event.hash signed by node private key.
	NodeSig []byte `protobuf:"bytes,2,opt,name=node_sig,json=nodeSig,proto3" json:"node_sig,omitempty"`
}

func (x *NewEventReceivedRequest) Reset() {
	*x = NewEventReceivedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internode_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewEventReceivedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewEventReceivedRequest) ProtoMessage() {}

func (x *NewEventReceivedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internode_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewEventReceivedRequest.ProtoReflect.Descriptor instead.
func (*NewEventReceivedRequest) Descriptor() ([]byte, []int) {
	return file_internode_proto_rawDescGZIP(), []int{0}
}

func (x *NewEventReceivedRequest) GetEvent() *Envelope {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *NewEventReceivedRequest) GetNodeSig() []byte {
	if x != nil {
		return x.NodeSig
	}
	return nil
}

type NewEventReceivedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NewEventReceivedResponse) Reset() {
	*x = NewEventReceivedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internode_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewEventReceivedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewEventReceivedResponse) ProtoMessage() {}

func (x *NewEventReceivedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internode_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewEventReceivedResponse.ProtoReflect.Descriptor instead.
func (*NewEventReceivedResponse) Descriptor() ([]byte, []int) {
	return file_internode_proto_rawDescGZIP(), []int{1}
}

type NewEventInPoolRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *NewEventInPoolRequest) Reset() {
	*x = NewEventInPoolRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internode_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewEventInPoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewEventInPoolRequest) ProtoMessage() {}

func (x *NewEventInPoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internode_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewEventInPoolRequest.ProtoReflect.Descriptor instead.
func (*NewEventInPoolRequest) Descriptor() ([]byte, []int) {
	return file_internode_proto_rawDescGZIP(), []int{2}
}

func (x *NewEventInPoolRequest) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type NewEventInPoolResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NewEventInPoolResponse) Reset() {
	*x = NewEventInPoolResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internode_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewEventInPoolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewEventInPoolResponse) ProtoMessage() {}

func (x *NewEventInPoolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internode_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewEventInPoolResponse.ProtoReflect.Descriptor instead.
func (*NewEventInPoolResponse) Descriptor() ([]byte, []int) {
	return file_internode_proto_rawDescGZIP(), []int{3}
}

var File_internode_proto protoreflect.FileDescriptor

var file_internode_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0a, 0x63, 0x61, 0x73, 0x61, 0x62, 0x6c, 0x61, 0x6e, 0x63, 0x61, 0x1a, 0x0e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x60, 0x0a,
	0x17, 0x4e, 0x65, 0x77, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x61, 0x73, 0x61, 0x62, 0x6c,
	0x61, 0x6e, 0x63, 0x61, 0x2e, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x52, 0x05, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x73, 0x69, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x53, 0x69, 0x67, 0x22,
	0x1a, 0x0a, 0x18, 0x4e, 0x65, 0x77, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2b, 0x0a, 0x15, 0x4e,
	0x65, 0x77, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x22, 0x18, 0x0a, 0x16, 0x4e, 0x65, 0x77, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x32, 0xc4, 0x01, 0x0a, 0x0a, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x6f, 0x4e, 0x6f, 0x64,
	0x65, 0x12, 0x5d, 0x0a, 0x10, 0x4e, 0x65, 0x77, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x64, 0x12, 0x23, 0x2e, 0x63, 0x61, 0x73, 0x61, 0x62, 0x6c, 0x61, 0x6e,
	0x63, 0x61, 0x2e, 0x4e, 0x65, 0x77, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x63, 0x61, 0x73,
	0x61, 0x62, 0x6c, 0x61, 0x6e, 0x63, 0x61, 0x2e, 0x4e, 0x65, 0x77, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x57, 0x0a, 0x0e, 0x4e, 0x65, 0x77, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x50, 0x6f,
	0x6f, 0x6c, 0x12, 0x21, 0x2e, 0x63, 0x61, 0x73, 0x61, 0x62, 0x6c, 0x61, 0x6e, 0x63, 0x61, 0x2e,
	0x4e, 0x65, 0x77, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x63, 0x61, 0x73, 0x61, 0x62, 0x6c, 0x61, 0x6e,
	0x63, 0x61, 0x2e, 0x4e, 0x65, 0x77, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x50, 0x6f, 0x6f,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1a, 0x5a, 0x18, 0x63, 0x61, 0x73,
	0x61, 0x62, 0x6c, 0x61, 0x6e, 0x63, 0x61, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internode_proto_rawDescOnce sync.Once
	file_internode_proto_rawDescData = file_internode_proto_rawDesc
)

func file_internode_proto_rawDescGZIP() []byte {
	file_internode_proto_rawDescOnce.Do(func() {
		file_internode_proto_rawDescData = protoimpl.X.CompressGZIP(file_internode_proto_rawDescData)
	})
	return file_internode_proto_rawDescData
}

var file_internode_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internode_proto_goTypes = []interface{}{
	(*NewEventReceivedRequest)(nil),  // 0: casablanca.NewEventReceivedRequest
	(*NewEventReceivedResponse)(nil), // 1: casablanca.NewEventReceivedResponse
	(*NewEventInPoolRequest)(nil),    // 2: casablanca.NewEventInPoolRequest
	(*NewEventInPoolResponse)(nil),   // 3: casablanca.NewEventInPoolResponse
	(*Envelope)(nil),                 // 4: casablanca.Envelope
}
var file_internode_proto_depIdxs = []int32{
	4, // 0: casablanca.NewEventReceivedRequest.event:type_name -> casablanca.Envelope
	0, // 1: casablanca.NodeToNode.NewEventReceived:input_type -> casablanca.NewEventReceivedRequest
	2, // 2: casablanca.NodeToNode.NewEventInPool:input_type -> casablanca.NewEventInPoolRequest
	1, // 3: casablanca.NodeToNode.NewEventReceived:output_type -> casablanca.NewEventReceivedResponse
	3, // 4: casablanca.NodeToNode.NewEventInPool:output_type -> casablanca.NewEventInPoolResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internode_proto_init() }
func file_internode_proto_init() {
	if File_internode_proto != nil {
		return
	}
	file_protocol_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_internode_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewEventReceivedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internode_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewEventReceivedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internode_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewEventInPoolRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internode_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewEventInPoolResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internode_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internode_proto_goTypes,
		DependencyIndexes: file_internode_proto_depIdxs,
		MessageInfos:      file_internode_proto_msgTypes,
	}.Build()
	File_internode_proto = out.File
	file_internode_proto_rawDesc = nil
	file_internode_proto_goTypes = nil
	file_internode_proto_depIdxs = nil
}
