import { defineProperties } from "@vanilla-extract/sprinkles";

export const blockProperties = defineProperties({
  properties: {
    position: {
      relative: "relative",
      absolute: "absolute",
      absoluteFill: {
        position: "absolute",
        top: 0,
        right: 0,
        bottom: 0,
        left: 0,
      },
      fixed: "fixed",
      static: "static",
      sticky: "sticky",
    },
    overflowX: ["hidden", "visible", "auto", "scroll"],
    overflowY: ["hidden", "visible", "auto", "scroll"],
    cursor: [
      "auto",
      "default",
      "none",
      "context-menu",
      "help",
      "pointer",
      "progress",
      "wait",
      "cell",
      "crosshair",
      "text",
      "vertical-text",
      "alias",
      "copy",
      "move",
      "no-drop",
      "not-allowed",
      "all-scroll",
      "col-resize",
      "row-resize",
      "n-resize",
      "e-resize",
      "s-resize",
      "w-resize",
      "ns-resize",
      "ew-resize",
      "ne-resize",
      "nw-resize",
      "se-resize",
      "sw-resize",
      "nesw-resize",
      "nwse-resize",
    ],
  },
  shorthands: {
    overflow: ["overflowX", "overflowY"],
  },
});
