version: '3'
services:
    redis:
        image: redis:latest
        container_name: stress-testing-redis
        ports:
            - '6379:6379'
    stress-00:
        build:
            context: ../../
            dockerfile: ./packages/stress-testing/Dockerfile
        env_file: .env
        environment:
            - CONTAINER_COUNT=2
            - CONTAINER_INDEX=0
            - SESSION_ID=${SESSION_ID}
        depends_on:
            - redis
    stress-01:
        build:
            context: ../../
            dockerfile: ./packages/stress-testing/Dockerfile
        env_file: .env
        environment:
            - CONTAINER_COUNT=2
            - CONTAINER_INDEX=1
            - SESSION_ID=${SESSION_ID}
        depends_on:
            - redis
