port: <RPC_PORT>
dburl: postgres://postgres:postgres@localhost:<DB_PORT>/casablanca?sslmode=disable&pool_max_conns=1000
storageType: postgres
address:
useContract: <USE_CONTRACT>
# HNT-2048 remove this line once RDK registration is implemented in the client
skipDelegateCheck: true
chain:
    chainId: 31337
    networkUrl: 'http://127.0.0.1:8545'
    # use v2 or v3. Defaults to v2 if unspecified or empty
    contractVersion: <CONTRACT_VERSION>
log:
    file: logs/dev.log
    level: info
    console: true
metrics:
    enabled: <METRICS_ENABLED>
    port: <METRICS_PORT>
