port: <RPC_PORT>
dburl: postgres://postgres:postgres@localhost:<DB_PORT>/casablanca?sslmode=disable&pool_max_conns=1000
storageType: postgres
address:
useContract: <USE_CONTRACT>
walletprivatekey:
chain:
    chainId: 31337
    networkUrl: 'http://127.0.0.1:8545'
topChain:
    chainId: 31337
    networkUrl: 'http://127.0.0.1:8545'
log:
    file: logs/dev.log
    level: <LOG_LEVEL>
    console: true
    noColor: <LOG_NOCOLOR>
    format: text
metrics:
    enabled: <METRICS_ENABLED>
    port: <METRICS_PORT>
# profiling is turned of by default (see profilngEnabled: false below)
performanceTracking:
    profilingEnabled: false
nodeRegistry: <NODE_REGISTRY>
pushNotification:
    url: '' # URL to the push notification worker. Default empty string disables it.
    authToken: '' # auth token for the push notification worker
stream:
    media:
        maxChunkCount: 10 # max number of chunks in a media stream
        maxChunkSize: 500000 # max number of bytes in a single chunk
useBlockchainStreamRegistry: <USE_BLOCKCHAIN_STREAM_REGISTRY>
