port: 5157
dburl: postgres://postgres:postgres@localhost:5433/casablanca?sslmode=disable&pool_max_conns=3
address:
log:
    file: logs/dev.log
    level: info
metrics:
    enabled: true
    port: 8081
