version: '2'
linters:
    enable:
        - exhaustive
    disable:
        - staticcheck
    settings:
        exhaustive:
            check:
                - switch
    exclusions:
        generated: lax
        presets:
            - comments
            - common-false-positives
            - legacy
            - std-error-handling
        paths:
            - third_party$
            - builtin$
            - examples$
formatters:
    enable:
        - goimports
        - golines
        - gofumpt
    settings:
        goimports:
            local-prefixes:
                - github.com/towns-protocol/towns
        golines:
            max-len: 120
            shorten-comments: false
            reformat-tags: true
            chain-split-dots: true
        gofumpt:
            module-path: github.com/towns-protocol/towns
    exclusions:
        generated: lax
        paths:
            - third_party$
            - builtin$
            - examples$
