main = "./src/index.ts"
name = "unfurl-worker"
compatibility_date = "2022-07-26"
node_compat=true
type="javascript"
# wrangler should be source of truth https://developers.cloudflare.com/workers/wrangler/configuration/#source-of-truth, so defining custom_domain here even though it causes issue in our use case:
# We are using a custom domain which is a subdomain of a zone that has no content, yet (zion.xyz). 
# This causes `wrangler dev` to fail https://github.com/cloudflare/wrangler2/issues/2149
# But `wrangler dev --local` (which is what our VSCode task uses) and publishing work fine. 
# If you really need `wrangler dev` for some reason, remove the following line temporarily
route = { pattern = "unfurl-proxy.zion.xyz", custom_domain = true }
account_id="9840f8a36a817b103e00e29a0e2bad6f"

# this is for tests, so it gets used even though wrangler CLI says otherwise
[miniflare]
cache_persist = false

[dev]
cache_persist = false
ip = "localhost"
port = 8007
local_protocol = "http"

[vars]
# VAR_NAME = "some_value"

# The necessary secrets are:
# TWITTER_BEARER
# for local development, you can add these in .dev.vars
# OR
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these