main = "./src/index.ts"
name = "unfurl-worker"
compatibility_date = "2022-07-26"
node_compat=true
type="javascript"
route = "unfurl.zion.xyz/*"
zone_id = "26d0d19e0a900688cc377ceb7ec0413d"
account_id="9840f8a36a817b103e00e29a0e2bad6f"

# this is for tests, so it gets used even though wrangler CLI says otherwise
[miniflare]
cache_persist = false

[dev]
cache_persist = false
ip = "localhost"
port = 8007
local_protocol = "http"

[vars]
# VAR_NAME = "some_value"

# The necessary secrets are:
# for local development, you can add these in .dev.vars
# OR
# TWITTER_BEARER
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these