services:
    river-node:
        build:
            dockerfile: ./Dockerfile
            context: ../
        ports:
            - '5180:5180'
        extra_hosts:
            - 'localhost:host-gateway'
        volumes:
            # attach local run_files to the container
            - ../run_files:/run_files
            - $HOME/towns-ca-cert.pem:/root/towns-ca-cert.pem
            - $HOME/towns-ca-key.pem:/root/towns-ca-key.pem
            - ../scripts/register-ca.sh:/register-ca.sh
