# Notification service specific configuration
# Inherits common settings from ../common/common.yaml

# Override HTTPS setting for local development
disableHttps: true

# Metrics configuration - using different port to avoid conflicts
metrics:
    port: 4143

# Notification service specific settings
notifications:
    simulate: true
    authentication:
        sessionToken:
            lifetime: 30m
            key:
                algorithm: HS256
                key: 'c69b1973792ad59bebb96a2ab1639aafc0c1e229a1c2138d91834f0f6953a544'
