disableBaseChain: true

appRegistry:
    appRegistryId: local-multi_ne
    sharedSecretDataEncryptionKey: '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef'
    allowInsecureWebhooks: true
    authentication:
        sessionToken:
            key:
                algorithm: 'hs256'
                key: '1111111122222222333333334444444455555555666666667777777788888888'

notifications:
    simulate: true
    authentication:
        sessionToken:
            lifetime: 30m
            key:
                algorithm: HS256
                key: 'c69b1973792ad59bebb96a2ab1639aafc0c1e229a1c2138d91834f0f6953a544'
