export const LoginTypePublicKey = "m.login.publickey";
export const LoginTypePublicKeyEthereum = "m.login.publickey.ethereum";

export enum LoginStatus {
  LoggedIn = "LoggedIn",
  LoggingIn = "LoggingIn",
  LoggingOut = "LoggingOut",
  LoggedOut = "LoggedOut",
  Registering = "Registering",
}

export interface AuthenticationError {
  code: number;
  message: string;
}

interface UserInteractiveFlow {
  stages: string[];
}

export interface PublicKeyEtheremParams {
  version: number;
  chain_ids: number[];
  nonce: string;
}

export interface LoginFlows {
  flows: LoginFlow[];
}
export interface AuthenticationData {
  type: string;
  address: string;
  session: string;
  message: string;
  signature: string;
}

export interface RegistrationAuthentication {
  type: string;
  session: string;
  public_key_response: AuthenticationData;
}

export interface RegisterRequest {
  // https://spec.matrix.org/v1.2/client-server-api/#post_matrixclientv3register
  auth: RegistrationAuthentication;
  username: string; // wallet address
  inhibit_login?: boolean;
  device_id?: string;
  initial_device_display_name?: string;
}

export interface Eip4361Info {
  authority: string; // is the RFC 3986 authority that is requesting the signing.
  address: string; // is the Ethereum address performing the signing conformant to capitalization encoded checksum specified in EIP-55 where applicable.
  version: string; // version of the Matrix public key spec that the client is complying with.
  chainId: number; // is the EIP-155 Chain ID to which the session is bound, and the network where Contract Accounts must be resolved.
  nonce: string; // is a randomized string used to prevent replay attacks. Generated by server. At least 8 alphanumeric characters.
  statement: string; // is a human-readable ASCII assertion that the user will sign, and it must not contain '\n' (the byte 0x0a).
}

interface UserInteractive {
  completed: string[];
  flows: UserInteractiveFlow[];
  session: string;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  params?: any;
}

interface LoginFlow {
  type: string;
}

export function getUsernameFromId(
  userId: string | undefined,
): string | undefined {
  if (userId) {
    const regexName = /^@(?<username>.*):/;
    const match = regexName.exec(userId);
    const username = match?.groups?.username ?? undefined;
    return username;
  }

  return undefined;
}

export function getShortUsername(userId: string): string {
  // Wallet address starts with 0x.....
  if (userId && userId.startsWith("0x") && userId.length === 42) {
    const last4 = userId.length - 4;
    return `${userId.slice(0, 5)}....${userId.slice(last4)}`;
  }
  return userId;
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function isLoginFlowPublicKeyEthereum(o: any): o is UserInteractive {
  if ((o as UserInteractive).flows !== undefined) {
    const flows = (o as UserInteractive).flows;
    for (const f of flows) {
      if (f.stages.includes(LoginTypePublicKeyEthereum)) {
        return true;
      }
    }
  }

  return false;
}

export function getParamsPublicKeyEthereum(
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  p: any,
): PublicKeyEtheremParams | undefined {
  const params = p[LoginTypePublicKeyEthereum];
  if (params !== undefined) {
    return params as PublicKeyEtheremParams;
  }
  return undefined;
}

export function getChainIdEip155(chainId: string): number {
  // ChainId should not have 0x prefix.
  // https://eips.ethereum.org/EIPS/eip-155
  const cid = chainId.replace(/0x/g, "");
  return cid ? parseInt(cid) : -1;
}

// https://chainlist.org/
// https://eips.ethereum.org/EIPS/eip-155#list-of-chain-ids
export function getChainName(chainId: number): string {
  switch (chainId) {
    case 1 || "0x1":
      return "Ethereum Mainnet";
    case 2 || "0x2":
      return "Expanse Mainnet";
    case 3 || "0x3":
      return "Ropsten Test Network";
    case 4 || "0x4":
      return "Rinkeby Test Network";
    case 5 || "0x5":
      return "Goerli Test Network";
    case 42 || "0x42":
      return "Kovan Test Network";
    case 56 || "0x56":
      return "Binance Smart Chain Mainnet";
    case 137 || "0x137":
      return "Polygon Mainnet";
    case 42161 || "0x42161":
      return "Arbitrum One";
    case 10 || "0x10":
      return "Optimism";
    case 100 || "0x100":
      return "Gnosis Chain";
    default:
      return chainId.toString();
  }
}
