import { defineProperties } from "@vanilla-extract/sprinkles";

export const blockProperties = defineProperties({
  properties: {
    position: ["relative", "absolute", "fixed", "static", "sticky"],
    overflow: ["hidden", "visible", "auto"],
    cursor: [
      "auto",
      "default",
      "none",
      "context-menu",
      "help",
      "pointer",
      "progress",
      "wait",
      "cell",
      "crosshair",
      "text",
      "vertical-text",
      "alias",
      "copy",
      "move",
      "no-drop",
      "not-allowed",
      "all-scroll",
      "col-resize",
      "row-resize",
      "n-resize",
      "e-resize",
      "s-resize",
      "w-resize",
      "ns-resize",
      "ew-resize",
      "ne-resize",
      "nw-resize",
      "se-resize",
      "sw-resize",
      "nesw-resize",
      "nwse-resize",
    ],
  },
});
