// @generated by protoc-gen-connect-web v0.6.0 with parameter "target=ts"
// @generated from file protocol.proto (package casablanca, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AddEventRequest, AddEventResponse, CreateStreamRequest, CreateStreamResponse, GetStreamRequest, GetStreamResponse, InfoRequest, InfoResponse, SyncStreamsRequest, SyncStreamsResponse } from "./protocol_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service casablanca.ZionService
 */
export const ZionService = {
  typeName: "casablanca.ZionService",
  methods: {
    /**
     * @generated from rpc casablanca.ZionService.CreateStream
     */
    createStream: {
      name: "CreateStream",
      I: CreateStreamRequest,
      O: CreateStreamResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc casablanca.ZionService.GetStream
     */
    getStream: {
      name: "GetStream",
      I: GetStreamRequest,
      O: GetStreamResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc casablanca.ZionService.AddEvent
     */
    addEvent: {
      name: "AddEvent",
      I: AddEventRequest,
      O: AddEventResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc casablanca.ZionService.SyncStreams
     */
    syncStreams: {
      name: "SyncStreams",
      I: SyncStreamsRequest,
      O: SyncStreamsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc casablanca.ZionService.Info
     */
    info: {
      name: "Info",
      I: InfoRequest,
      O: InfoResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

