chain:
    - network_url: 'http://localhost:8545'
      chain_id: 1
    - network_url: 'http://localhost:8546'
      chain_id: 2
entitlement_contract:
    url: 'ws://localhost:8546'
    chainId: 
    address: 
test_contract:
    url: 'ws://localhost:8546'
    chainId: 
    address:
log:
    file: logs/dev.log
    level: info
    console: true
metrics:
    enabled: true
    port: 
