import { defineConfig } from '@wagmi/cli'
import { foundry } from '@wagmi/cli/plugins'

export default defineConfig({
    out: 'typings/index.ts',
    plugins: [
        foundry({
            project: '../',
            artifacts: 'contracts/out',
            include: [
                '**/IDiamond.sol/*.json',
                '**/IDiamondCut.sol/*.json',
                '**/IArchitect.sol/*.json',
                '**/ILegacyArchitect.sol/*.json',
                '**/IProxyManager.sol/*.json',
                '**/IPausable.sol/*.json',
                '**/IEntitlementsManager.sol/*.json',
                '**/IChannel.sol/*.json',
                '**/IRoles.sol/*.json',
                '**/IMulticall.sol/*.json',
                '**/IRuleEntitlement.sol/*.json',
                '**/IRuleEntitlementV2.sol/*.json',
                '**/IWalletLink.sol/*.json',
                '**/INodeRegistry.sol/*.json',
                '**/IOperatorRegistry.sol/*.json',
                '**/IStreamRegistry.sol/*.json',
                '**/IERC173.sol/*.json',
                '**/ITokenPausableFacet.sol/*.json',
                '**/IUserEntitlement.sol/*.json',
                '**/ISpaceOwner.sol/*.json',
                '**/IMembershipFacet.sol/*.json',
                '**/IMembershipMetadata.sol/*.json',
                '**/IBanning.sol/*.json',
                '**/IPricingModules.sol/*.json',
                '**/ICrossChainEntitlement.sol/*.json',
                '**/IPrepayFacet.sol/*.json',
                '**/IERC721AQueryable.sol/*.json',
                '**/IEntitlementDataQueryable.sol/*.json',
                '**/IPlatformRequirementsFacet.sol/*.json',
                '**/IERC721A.sol/*.json',
                '**/INodeOperator.sol/*.json',
                '**/ISpaceDelegation.sol/*.json',
                '**/IEntitlementChecker.sol/*.json',
                '**/IERC5267.sol/*.json',
                '**/ICreateSpace.sol/*.json',
                '**/IDropFacet.sol/*.json',
                '**/ITownsPoints.sol/*.json',
                '**/ITipping.sol/*.json',
                '**/IReview.sol/*.json',
            ],
            forge: {
                build: false,
            },
        }),
    ],
})
