version: '3'

services:
  bundler:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "14337:14337"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: ./skandha standalone --redirectRpc --unsafeMode
