export const PATHS = {
    SPACES: 't',
    CHANNELS: 'channels',
    REPLIES: 'replies',
    REGISTER: 'register',
    GETTING_STARTED: 'getting-started',
    MENTIONS: 'mentions',
    MEMBERS: 'members',
    THREADS: 'threads',
    SETTINGS: 'settings',
    LOGIN: 'login',
    VERSIONS: 'versions',
    ROLES: 'roles',
    MESSAGES: 'messages',
    PROFILE: 'profile',
} as const
