#!/bin/bash
set -ueo pipefail
cd -P -- "$(dirname -- "${BASH_SOURCE[0]}")"
cd ..

CHAIN="${1:-localhost}"
FROZEN="${2:-}"
ABI_DIR="packages/generated/${CHAIN}/v3/abis"

forge build

yarn typechain --target=ethers-v5 "contracts/out/**/?(IDiamond|IDiamondCut|ITownArchitect|IProxyManager|IPausable|IEntitlementsManager|IChannel|IRoles|IMulticall|TokenEntitlement|IWalletLink|OwnableFacet|TokenPausableFacet|UserEntitlement|ITownOwner|MockERC721A|MembershipFacet|Member).json" --out-dir "packages/generated/${CHAIN}/v3/typings"

mkdir -p $ABI_DIR && cp -a contracts/out/{Diamond,DiamondCutFacet,TownArchitect,ProxyManager,Pausable,EntitlementsManager,Channels,Roles,Multicall,OwnableFacet,TokenEntitlement,WalletLink,TokenPausableFacet,UserEntitlement,TownOwner,MockERC721A,MembershipFacet,Member,IEntitlementRule,MockRiverRegistry}.sol/* "$ABI_DIR"

# Copy the json abis to TS files for type inference
for file in $ABI_DIR/*.abi.json; do
  filename=$(basename  "$file" .json)
  echo "export default $(cat $file) as const" > $ABI_DIR/$filename.ts
done

./scripts/gen-river-node-bindings.sh $CHAIN
./scripts/gen-xchain-bindings.sh $CHAIN

# Using the $FROZEN flag and git diff, we can check if this script generates any new files
# under the $ABI_DIR directory.
if [ "$FROZEN" = "--frozen" ]; then
  if git diff --quiet --exit-code $ABI_DIR; then
    echo "No new files generated by build-town-types.sh"
  else
    echo "$(git diff -p $ABI_DIR)"
    echo "Error: build-town-types.sh generated new files with the --frozen flag. Please re-run ./scripts/build-town-types.sh to re-generate the files and commit the changes."
    exit 1
  fi
fi
