#!/bin/bash

CHAIN="${1:-localhost}"

forge clean
forge build --extra-output-files metadata --extra-output-files abi --force

ABI_DIR="packages/generated/${CHAIN}/abis"
TYPINGS_DIR="servers/dendrite/zion/contracts/zion_${CHAIN}"

# A command line option to exit with a failure status if this script generates any new files.
# Example usage:
# ./scripts/build-contract-types.sh localhost --frozen
FROZEN="${2:-}"

# Create typings using typechain
yarn typechain --target=ethers-v5 "contracts/out/**/?(Events|Errors|Member|CouncilStaking|IEntitlement|TokenEntitlement|UserEntitlement|Space|SpaceFactory|Pioneer|Mock721).json" --out-dir "packages/generated/${CHAIN}/typings"

# Move abis to the packages folder
mkdir -p $ABI_DIR && cp -a contracts/out/{Events,Errors,Member,CouncilStaking,entitlements/IEntitlement,TokenEntitlement,UserEntitlement,Space,SpaceFactory,Pioneer}.sol/* "packages/generated/${CHAIN}/abis"

# Copy the json abis to TS files for type inference
for file in $ABI_DIR/*.abi.json; do
  filename=$(basename  "$file" .json)
  echo "export default $(cat $file) as const" > $ABI_DIR/$filename.ts
done

# Move typings to the dendrite folder
mkdir -p $TYPINGS_DIR

# Create space factory v2 typings
mkdir -p "servers/dendrite/zion/contracts/${CHAIN}_space_factory"
go run github.com/ethereum/go-ethereum/cmd/abigen@v1.10.25 --abi contracts/out/SpaceFactory.sol/SpaceFactory.abi.json --pkg "${CHAIN}_space_factory" --type "${CHAIN}_space_factory" --out "servers/dendrite/zion/contracts/${CHAIN}_space_factory/${CHAIN}_space_factory.go"

# Create space v2 typings
mkdir -p "servers/dendrite/zion/contracts/${CHAIN}_space"
go run github.com/ethereum/go-ethereum/cmd/abigen@v1.10.25 --abi contracts/out/Space.sol/Space.abi.json --pkg "${CHAIN}_space"  --type "${CHAIN}_space" --out "servers/dendrite/zion/contracts/${CHAIN}_space/${CHAIN}_space.go"

# Using the $FROZEN flag and git diff, we can check if this script generates any new files
# under the $ABI_DIR or $TYPINGS_DIR directories.
if [ "$FROZEN" = "--frozen" ]; then
  if git diff --quiet --exit-code $ABI_DIR $TYPINGS_DIR; then
    echo "No new files generated by build-contract-types.sh"
  else
    echo "$(git diff -p $ABI_DIR $TYPINGS_DIR)"
    echo "Error: build-contract-types.sh generated new files with the --frozen flag. Please re-run ./scripts/build-contract-types.sh to re-generate the files and commit the changes."
    exit 1
  fi
fi
