#!/bin/bash
set -ueo pipefail
cd -P -- "$(dirname -- "${BASH_SOURCE[0]}")"
cd ..

VERSION="${1:-localhost}"
if [ "$VERSION" = "localhost" ]; then
  VERSION="dev"
elif [ "$VERSION" = "base_sepolia" ]; then
  VERSION="v3"
fi
FROZEN="${2:-}"
ABI_DIR="packages/generated/${VERSION}/abis"

forge build

CONTRACT_INTERFACES="(IDiamond|IDiamondCut|ITownArchitect|IProxyManager|IPausable|IEntitlementsManager|IChannel|IRoles|IMulticall|TokenEntitlement|IWalletLink|IRiverRegistry|OwnableFacet|TokenPausableFacet|UserEntitlement|ITownOwner|MockERC721A|MembershipFacet|Member)"

yarn typechain --target=ethers-v5 "contracts/out/**/?${CONTRACT_INTERFACES}.json" --out-dir "packages/generated/${VERSION}/typings"

mkdir -p $ABI_DIR && cp -a contracts/out/{Diamond,DiamondCutFacet,TownArchitect,ProxyManager,Pausable,EntitlementsManager,Channels,Roles,Multicall,OwnableFacet,TokenEntitlement,WalletLink,RiverRegistry,TokenPausableFacet,UserEntitlement,TownOwner,MockERC721A,MembershipFacet,Member,IEntitlementRule,MockRiverRegistry}.sol/* "$ABI_DIR"

# Copy the json abis to TS files for type inference
for file in $ABI_DIR/*.abi.json; do
  filename=$(basename  "$file" .json)
  echo "export default $(cat $file) as const" > $ABI_DIR/$filename.ts
done

./scripts/gen-river-node-bindings.sh $VERSION
./scripts/gen-xchain-bindings.sh $VERSION

# Using the $FROZEN flag and git diff, we can check if this script generates any new files
# under the $ABI_DIR directory.
if [ "$FROZEN" = "--frozen" ]; then
  if git diff --quiet --exit-code $ABI_DIR; then
    echo "No new files generated by build-town-types.sh"
  else
    echo "$(git diff -p $ABI_DIR)"
    echo "Error: build-town-types.sh generated new files with the --frozen flag. Please re-run ./scripts/build-town-types.sh to re-generate the files and commit the changes."
    exit 1
  fi
fi
