#!/bin/bash

CHAIN="${1:-localhost}"

forge clean
forge build --extra-output-files metadata --extra-output-files abi --force

ABI_DIR="packages/contracts/${CHAIN}/abis"
TYPINGS_DIR="servers/dendrite/zion_${CHAIN}"

# A command line option to exit with a failure status if this script generates any new files.
# Example usage:
# ./scripts/build-contract-types.sh localhost --frozen
FROZEN="${2:-}"

# Create typings using typechain
yarn typechain --target=ethers-v5 "out/**/?(Errors,Events,CouncilNFT|CouncilStaking|ZionSpaceManager|ZionRoleManager|TokenEntitlementModule|UserGrantedEntitlementModule).json" --out-dir "packages/contracts/${CHAIN}/typings"

# Move abis to the packages folder
mkdir -p $ABI_DIR && cp -a out/{Errors,Events,CouncilNFT,CouncilStaking,ZionSpaceManager,ZionRoleManager,TokenEntitlementModule,UserGrantedEntitlementModule}.sol/* "packages/contracts/${CHAIN}/abis"

# Move typings to the dendrite folder
mkdir -p $TYPINGS_DIR && go run github.com/ethereum/go-ethereum/cmd/abigen@v1.10.25 --abi out/ZionSpaceManager.sol/ZionSpaceManager.abi.json --pkg "zion_${CHAIN}"  --type "zion_space_manager_${CHAIN}" --out "servers/dendrite/zion/contracts/zion_${CHAIN}/zion_space_manager_${CHAIN}.go"

# Using the $FROZEN flag and git diff, we can check if this script generates any new files
# under the $ABI_DIR or $TYPINGS_DIR directories.
if [ "$FROZEN" = "--frozen" ]; then
  if git diff --quiet --exit-code $ABI_DIR $TYPINGS_DIR; then
    echo "No new files generated by build-contract-types.sh"
  else
    echo "Error: build-contract-types.sh generated new files with the --frozen flag. Please re-run ./scripts/build-contract-types.sh to re-generate the files and commit the changes."
    exit 1
  fi
fi
