#!/bin/bash

# very similar to running git clean -xd however, we don't want to remove
# .env.local files, dendrite keys (if you're running from vs), etc
# if you want to clean everything temporary created by the build, but 
# don't want a full reset on your dev environment, this is the script for you

pushd "$(git rev-parse --show-toplevel)"
echo "cleaning node"

yarn cache clean

# remove temp files generated by yarn, turbo, build, etc
find . -name "node_modules" -type d -exec rm -r "{}" \;
find . -name "dist" -type d -exec rm -r "{}" \;
find . -name "bin" -type d -exec rm -r "{}" \;
find . -name "coverage" -type d -exec rm -r "{}" \;
find . -name "out" -type d -exec rm -r "{}" \;
find . -name "gen" -type d -exec rm -r "{}" \;
find . -name ".turbo" -type d -exec rm -r "{}" \;
find . -name "tsconfig.tsbuildinfo" -type f -exec rm -r "{}" \;
find . -name ".eslintcache" -type f -exec rm -r "{}" \;

# remove ds_store files and delete empty directories
find . -type d -not -path "./.git/*" -print0 | while IFS= read -r -d '' dir; do
    content_count=$(find "$dir" -mindepth 1 -maxdepth 1 ! -name ".DS_Store" | wc -l)
    if [ "$content_count" -eq 0 ]; then
        echo "Deleting empty directory: $dir"
        rm -r "$dir"
    fi
done

popd
