# Blockchain configuration
baseChain:
    chainId: 84532
    networkUrl: 'https://sepolia.base.org'
    blockTimeMs: 2000
riverChain:
    chainId: 6524490
    networkUrl: 'https://testnet.rpc.towns.com'
    blockTimeMs: 2000

# Base contracts
architectContract:
    address: '0x968696BC59431Ef085441641f550C8e2Eaca8BEd'

appRegistryContract:
    address: '0xec3081A4b07678C12Fc6B56f69F894EE9e732c42'

entitlement_contract:
    address: '0x08cC41b782F27d62995056a4EF2fCBAe0d3c266F'

# River contracts
registryContract:
    address: '0xf18E98D36A6bd1aDb52F776aCc191E69B491c070'
