name = "push-notification-worker"
main = "src/index.ts"
account_id = "9840f8a36a817b103e00e29a0e2bad6f"
compatibility_date = "2023-05-18"
compatibility_flags = [ "nodejs_compat" ]

d1_databases = [
  { binding = "DB", database_name = "PushSubscription_test", database_id = "e6cdffba-1799-407f-af82-cda4a7c3da27" }
]

[dev]
ip = "127.0.0.1"
port = 8787
local_protocol = "http"

[vars]
ENVIRONMENT = "development"
VAPID_SUBJECT = "mailto:test@test.test"

# The necessary secrets are:
# AUTH_SECRET
# VAPID_PUBLIC_KEY
# VAPID_PRIVATE_KEY
#
# for local development, you can add these in .dev.vars
#
# for test, you can add these in the Cloudflare dashboard or run
# `echo <VALUE> | npx wrangler secret put <NAME> --env test` for each of these
#
# for production, the secrets must be deployed behind the production flag
# `echo <VALUE> | npx wrangler secret put <NAME> --env production`

[env.test]
name = "push-notification-worker-test"
d1_databases = [
  { binding = "DB", database_name = "PushSubscription_test", database_id = "e6cdffba-1799-407f-af82-cda4a7c3da27"}
]
vars = { ENVIRONMENT = "test", VAPID_SUBJECT = "mailto:test@towns.com" }

[env.production]
name = "push-notification-worker-production"
d1_databases = [
  { binding = "DB", database_name = "PushSubscription", database_id = "41e2c89e-1d22-41c3-b5e5-d936d9c67af7"}
]
vars = { ENVIRONMENT = "production", VAPID_SUBJECT = "mailto:support@towns.com" }

# [env.shared]
# SHARED_VARIABLE = "shared_value"
