name = "push-notification-worker"
main = "src/index.ts"
account_id = "9840f8a36a817b103e00e29a0e2bad6f"
compatibility_date = "2023-07-10"
node_compat = true
logpush = true

d1_databases = [
  { binding = "DB", database_name = "PushSubscription_test", database_id = "e6cdffba-1799-407f-af82-cda4a7c3da27" },
]

[dev]
ip = "127.0.0.1"
port = 8787
local_protocol = "http"

[vars]
ENVIRONMENT = "development"
VAPID_SUBJECT = "mailto:test@test.test"

# The necessary secrets are:
# AUTH_SECRET
# VAPID_PUBLIC_KEY
# VAPID_PRIVATE_KEY
#
# for local development, you can add these in .dev.vars
#
# for test, you can add these in the Cloudflare dashboard or run
# `echo <VALUE> | npx wrangler secret put <NAME> --env test` for each of these
#
# for production, the secrets must be deployed behind the production flag
# `echo <VALUE> | npx wrangler secret put <NAME> --env production`
# to create D1 db
# wrangler d1 create <DATABASE_NAME>


[env.production]
name = "push-notification-worker-production"
d1_databases = [
  { binding = "DB", database_name = "PushSubscription", database_id = "41e2c89e-1d22-41c3-b5e5-d936d9c67af7" },
]
vars = { ENVIRONMENT = "production", VAPID_SUBJECT = "mailto:support@towns.com" }

[env.test-beta]
name = "push-notification-worker-test-beta"
d1_databases = [
  { binding = "DB", database_name = "PushSubscription_test_beta", database_id = "d4a9236f-58ee-4e34-99d4-0cef0d2afd4d" },
]
routes = [
  { pattern = "push-notification-worker-test-beta.towns.com", custom_domain = true },
]
vars = { ENVIRONMENT = "test-beta", VAPID_SUBJECT = "mailto:test@towns.com" }


[env.staging-beta]
name = "push-notification-worker-staging-beta"
d1_databases = [
  { binding = "DB", database_name = "PushSubscription_staging_beta", database_id = "a582fd79-3e08-4a8b-a72e-6862e33a9027" },
]
routes = [
  { pattern = "push-notification-worker-staging-beta.towns.com", custom_domain = true },
]
vars = { ENVIRONMENT = "staging-beta", VAPID_SUBJECT = "mailto:staging@towns.com" }

[env.production-beta]
name = "push-notification-worker-production-beta"
d1_databases = [
  { binding = "DB", database_name = "PushSubscription_beta", database_id = "e2a212f4-eb8b-43a1-b60a-9cecf9dad6bf" },
]
routes = [
  { pattern = "push-notification-worker-production-beta.towns.com", custom_domain = true },
]
vars = { ENVIRONMENT = "production-beta", VAPID_SUBJECT = "mailto:support@towns.com" }
