name: river
services:
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:latest
        restart: always
        ports:
            - '8080:80'
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@localhost.localdomain
            - PGADMIN_DEFAULT_PASSWORD=postgres
            - PGADMIN_CONFIG_SERVER_MODE=False
            - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
            - PGADMIN_CONFIG_CHECK_EMAIL_DELIVERABILITY=False
            - PGADMIN_CONFIG_ALLOW_INVALID_EMAIL=True
        volumes:
            - ./pgadmin.json:/pgadmin4/servers.json
