version: "3.8"
# By default, the platform is linux/amd64
# see this https://discord.com/channels/874596133148696576/942772249662996520/1237294294214377502
# can't get this working on mac
# ci runs w/ linux/amd64
# this is a workaround to run on mac

services:
  contracts:
    build:
      context: ./contracts
      dockerfile: Dockerfile
    environment:
      - ANVIL_RPC=${ANVIL_RPC:-http://host.docker.internal:8545}
      # Uncomment this if you want to use the forked version
      #- SKIP_DEPLOYMENTS=true

  caddy:
    image: caddy:2-alpine
    ports:
      - "43370:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      bundler:
        condition: service_healthy

  bundler:
    build:
      context: ./bundler
      dockerfile: Dockerfile
    # Ports now exposed via caddy proxy
    environment:
      - ANVIL_RPC=${ANVIL_RPC:-http://host.docker.internal:8545}
    depends_on:
      contracts:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD-SHELL", "netstat -an | grep 4337 > /dev/null; if [ 0 != $? ]; then exit 1; fi;"]
      start_interval: 250ms
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 50

  mock-paymaster:
    build:
      context: ./mock-paymaster
      dockerfile: Dockerfile
    ports: ["43371:3000"]
    environment:
      - BUNDLER_RPC=http://caddy:80 # Point to the caddy proxy
      - ANVIL_RPC=${ANVIL_RPC:-http://host.docker.internal:8545}
    depends_on:
      bundler:
        condition: service_healthy
      contracts:
        condition: service_completed_successfully