main = "./src/index.ts"
name = "siwe-worker"
compatibility_date = "2023-01-18"
account_id="9840f8a36a817b103e00e29a0e2bad6f"
minify = true

[dev]
ip = "localhost"
port = 8005
local_protocol = "http"

[vars]
ENVIRONMENT = "development"
VERIFY = "true"

# The necessary secrets are:
# AUTH_SECRET
# ALCHEMY_API_KEY
#
# for local development, you can add these in .dev.vars
#
# For production, you can add these in the Cloudflare dashboard or run
# `echo <VALUE> | wrangler secret put <NAME>` for each of these
# for staging, the secrets must be deployed behind the staging flag
# `echo <VALUE> | wrangler secret put <NAME> --env staging`
# OR
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these

# staging routes
# yarn publish:stage
[env.staging]
workers_dev = true
routes = [{ pattern = "siwe-worker-staging.zion.xyz", custom_domain = true }, { pattern = "siwe-worker-staging.towns.com", custom_domain = true } ]
vars = { ENVIRONMENT = "staging", VERIFY = "true" } # [vars] access, not secrets

# production routes
# yarn publish:prod
[env.production]
route = [{ pattern = "siwe-worker.zion.xyz", custom_domain = true }, { pattern = "siwe-worker.towns.com", custom_domain = true }]
vars = { ENVIRONMENT = "production", VERIFY = "true" }