version: '3'
services:
  forked-chain-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - CLUSTER_NAME=transient-global-river-ecs-cluster
      - CLOUDFLARE_ZONE_ID=c69eaa5bc5b4d85a7055d70bcc2d038a
      - NODE_NAME=river1-transient-5168
      - AWS_REGION=us-east-1

      - CLOUDFLARE_API_TOKEN=
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=