name: Continuous Integration
on:
    push:
        branches:
            - main
    pull_request:

jobs:
    check:
        runs-on: ubuntu-latest
        timeout-minutes: 15
        services:
            redis:
                image: redis:latest
                options: >-
                    --health-cmd "redis-cli ping"
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                    - 55000:6379

            anvil:
                image: ghcr.io/foundry-rs/foundry:latest
                ports:
                    - 8545:8545
                options: >-
                    --entrypoint anvil

            postgres-casablanca:
                image: postgres:latest
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                ports:
                    # Maps tcp port 5433 on service container to the host
                    - 5433:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

            postgres-dendrite:
                image: postgres:14
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Git submodules
              run: git submodule update --init --recursive

            - name: Cancel previous runs
              uses: styfle/cancel-workflow-action@0.11.0
              with:
                  access_token: ${{ github.token }}

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1
              with:
                  version: nightly

            - uses: actions/setup-node@v3
              with:
                  node-version: '18'
                  cache: 'yarn'

            - name: Install node dependencies
              run: yarn install --immutable

            # TODO: this script has confusing relative pathing
            # - name: Install forge dependencies
            #   run: ./scripts/install-deps.sh

            - name: Syncpack
              run: yarn syncpack:check

            - name: Lint
              run: yarn lint

            - name: Build
              run: yarn build

            - name: Publish:local smart contracts
              run: yarn publish:local

            # TODO: fix the deploy script and make sure it can connect to
            # - name: Deploy local zion governance contracts
            #   run: ./scripts/deploy-local-zion-governance-contracts.sh

            - name: Casablanca create db
              run: psql -h localhost -p 5433 -U postgres -f scripts/sql/create_db.sql
              working-directory: casablanca
              env:
                  POSTGRES_PASSWORD: postgres
                  PGPASSWORD: postgres

            - name: Start dendrite
              run: ./servers/dendrite_local_test/run_single.sh 0 &

            - name: Test
              run: yarn test

            - name: Run Casablanca node
              run: yarn csb:start &

            - name: Wait for Casablanca node to be up
              run: yarn csb:wait

            - name: Test Casablanca node
              run: yarn csb:test-remote
