name: Continuous Integration
env:
    FOUNDRY_VERSION: nightly
    RIVER_BLOCK_TIME: 1
on:
    schedule:
        # run during working hours
        - cron: '0 15-23 * * *'
    pull_request:
    workflow_dispatch: # Allow manual trigger in GitHub UI
        inputs:
            skip_common_ci:
                description: Skip Common CI checks (i.e linting, prettier, etc)
                required: false
                default: false
                type: boolean
            skip_client_noentitlements:
                description: Skip Client Tests without entitlements
                required: false
                default: false
                type: boolean
            skip_multinode:
                description: Skip Multi-node Tests
                required: false
                default: false
                type: boolean
            skip_client_entitlements:
                description: Skip Client Tests with entitlements
                required: false
                default: false
                type: boolean
            skip_multinode_ent:
                description: Skip Multi-node Ent Tests
                required: false
                default: false
                type: boolean
            skip_node:
                description: Skip Node Tests
                required: false
                default: false
                type: boolean
            skip_xchain_node:
                description: Skip XChain Node Tests
                required: false
                default: false
                type: boolean

jobs:
    Common_CI:
        permissions: write-all
        if: github.event_name != 'workflow_dispatch' || !inputs.skip_common_ci
        runs-on: ubuntu-latest-8-cores
        timeout-minutes: 30

        steps:
            - name: Print bash environment
              run: env

            - name: Cancel previous runs
              if: github.event_name != 'schedule'
              uses: styfle/cancel-workflow-action@0.11.0
              with:
                  access_token: ${{ github.token }}

            - name: Checkout code
              uses: actions/checkout@v4

            - name: Git submodules
              run: git submodule update --init --recursive

            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                  go-version-file: 'river/go.work'
                  cache-dependency-path: '**/*.sum'

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1
              with:
                  version: ${{ env.FOUNDRY_VERSION }}

            - name: Install Forge modules
              run: ./river/scripts/install-deps.sh

            - uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'yarn'

            - name: Print versions
              run: ./scripts/print-versions.sh
              
            - name: Start and configure blockchains
              run: ./river/scripts/bc-all-start.sh

            - name: Install node dependencies
              run: yarn install --immutable

            - name: Maintain Turbo cache
              uses: actions/cache@v4
              with:
                  path: node_modules/.cache/turbo
                  key: ${{ runner.os }}-turbo-${{ github.run_id }}
                  restore-keys: |
                      ${{ runner.os }}-turbo-

            - name: Syncpack
              run: yarn syncpack:check

            - name: Build
              run: yarn build

            - name: Prettier
              run: yarn prettier:check

            - name: Lint
              run: yarn lint

            - name: Unit Tests
              run: yarn test:unit

            # If CI failed, we send a slack notification
            - name: Slack notification
              if: failure() && (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch')
              uses: rtCamp/action-slack-notify@v2
              env:
                  SLACK_WEBHOOK: ${{ secrets.SLACK_CI_CHANNEL_WEBHOOK_URL }}
                  SLACK_TITLE: 'Failure'
                  SLACK_USERNAME: 'CI'
                  SLACK_ICON_EMOJI: ':boom:'
                  SLACK_COLOR: '#FF0000'
                  SLACK_MESSAGE: 'CI Failure on ${{ github.repository }}'

    Multinode_Ent:
        permissions: write-all
        if: github.event_name != 'workflow_dispatch' || !inputs.skip_multinode_ent
        runs-on: ubuntu-latest-8-cores
        timeout-minutes: 30
        services:
            postgres-core:
                image: postgres:latest
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                ports:
                    # Maps tcp port 5433 on service container to the host
                    - 5433:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                    --name river_postgres_container

        steps:
            - name: Cancel previous runs
              if: github.event_name != 'schedule'
              uses: styfle/cancel-workflow-action@0.11.0
              with:
                  access_token: ${{ github.token }}

            - name: Show PostgreSQL max_connections
              run: psql -h localhost -p 5433 -U postgres -c 'SHOW max_connections;'
              env:
                  POSTGRES_PASSWORD: postgres
                  PGPASSWORD: postgres

            - name: Increase max_connections in Postgres
              run: |
                  docker exec -i river_postgres_container bash << EOF
                    echo 'max_connections = 1000' >> /var/lib/postgresql/data/postgresql.conf
                    echo 'shared_buffers = 2GB' >> /var/lib/postgresql/data/postgresql.conf
                  EOF
                  docker restart --time 0 river_postgres_container
                  sleep 5

            - name: Show PostgreSQL max_connections
              run: psql -h localhost -p 5433 -U postgres -c 'SHOW max_connections;'
              env:
                  POSTGRES_PASSWORD: postgres
                  PGPASSWORD: postgres

            - name: Checkout code
              uses: actions/checkout@v4

            - name: Git submodules
              run: git submodule update --init --recursive

            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                  go-version-file: 'river/go.work'
                  cache-dependency-path: '**/*.sum'

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1
              with:
                  version: ${{ env.FOUNDRY_VERSION }}

            - name: Install Forge modules
              run: ./river/scripts/install-deps.sh

            - uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'yarn'

            - name: Print versions
              run: ./scripts/print-versions.sh

            - name: Start and configure blockchains
              run: ./river/scripts/bc-all-start.sh

            - name: Install node dependencies
              run: yarn install --immutable

            - name: Print Yarn package versions
              run: yarn info --name-only --all

            - name: Maintain Turbo cache
              uses: actions/cache@v4
              with:
                  path: node_modules/.cache/turbo
                  key: ${{ runner.os }}-turbo-${{ github.run_id }}
                  restore-keys: |
                      ${{ runner.os }}-turbo-

            - name: create db
              run: psql -h localhost -p 5433 -U postgres -f scripts/sql/create_db.sql
              working-directory: river/core
              env:
                  POSTGRES_PASSWORD: postgres
                  PGPASSWORD: postgres

            - name: Setup River CA for testing certificates
              run: ./scripts/register-ca.sh
              working-directory: river/core

            - name: Set up Custom CA Certificate for Node.js
              run: |
                echo "NODE_EXTRA_CA_CERTS=$HOME/river-ca-cert.pem" >> $GITHUB_ENV

            - name: Run multiple nodes
              run: |
                  cd ./river/core/node
                  ./run_multi.sh -c -r &
                  for i in {5170..5179}; do yarn wait-on https://localhost:$i/debug/multi --timeout=400000 --i=5000 --verbose; done

            - name: Build & Test (with entitlements)
              run: CASABLANCA_SERVER_URL=https://localhost:5170,https://localhost:5171,https://localhost:5172,https://localhost:5173,https://localhost:5174,https://localhost:5175,https://localhost:5176,https://localhost:5177,https://localhost:5178,https://localhost:5179 yarn csb:turbo-no-sdk

            - name: Archive River Node Logs and Settings
              if: always()
              uses: actions/upload-artifact@v3
              with:
                  name: 'river-node-${{ github.job }}'
                  path: |
                      ./river/core/node/run_files/
                      !./river/core/node/run_files/**/bin/**

            # If CI failed, we send a slack notification
            - name: Slack notification
              if: failure() && (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch')
              uses: rtCamp/action-slack-notify@v2
              env:
                  SLACK_WEBHOOK: ${{ secrets.SLACK_CI_CHANNEL_WEBHOOK_URL }}
                  SLACK_TITLE: 'Failure'
                  SLACK_USERNAME: 'CI'
                  SLACK_ICON_EMOJI: ':boom:'
                  SLACK_COLOR: '#FF0000'
                  SLACK_MESSAGE: 'CI Failure on ${{ github.repository }}'