name: Continuous Integration
on:
    schedule:
        # run every 30 minutes
        - cron: '*/30 * * * *'
    pull_request:
    workflow_dispatch: # Allow manual trigger in GitHub UI
        inputs:
            skip_dendrite:
                description: Skip Dendrite Tests
                required: false
                default: false
                type: boolean
            skip_casablanca_client_noauth:
                description: Skip Casablanca Client Tests without Auth
                required: false
                default: false
                type: boolean
            skip_casablanca_client_auth:
                description: Skip Casablanca Client Tests with Auth
                required: false
                default: false
                type: boolean
            skip_casablanca_node:
                description: Skip Casablanca Node Tests
                required: false
                default: false
                type: boolean

jobs:
    Dendrite:
        permissions: write-all
        if: github.event_name != 'workflow_dispatch' || !inputs.skip_dendrite
        runs-on: ubuntu-latest-8-cores
        timeout-minutes: 30
        services:
            postgres-dendrite:
                image: postgres:latest
                env:
                    POSTGRES_USER: dendrite
                    POSTGRES_PASSWORD: itsasecret
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        steps:
            - name: Cancel previous runs
              if: github.event_name != 'schedule'
              uses: styfle/cancel-workflow-action@0.11.0
              with:
                  access_token: ${{ github.token }}

            - name: Checkout code
              uses: actions/checkout@v3

            - name: Git submodules
              run: git submodule update --init --recursive

            - name: Setup Go
              uses: actions/setup-go@v3
              with:
                  go-version: '1.20'
                  cache: true
                  cache-dependency-path: 'servers/**/go.sum'

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1
              with:
                  version: nightly

            - name: Install Forge modules
              run: ./scripts/install-deps.sh

            - uses: actions/setup-node@v3
              with:
                  node-version: '20'
                  cache: 'yarn'

            - name: Install node dependencies
              run: yarn install --immutable

            - name: Maintain Turbo cache
              uses: actions/cache@v3
              with:
                  path: node_modules/.cache/turbo
                  key: ${{ runner.os }}-turbo-${{ github.run_id }}
                  restore-keys: |
                      ${{ runner.os }}-turbo-

            - name: Syncpack
              run: yarn syncpack:check

            - name: Build
              run: yarn build

            - name: Prettier
              run: yarn prettier:check

            - name: Lint
              run: yarn lint

            - name: Build contract types
              run: ./scripts/build-contract-types.sh localhost --frozen

            - name: Start dendrite
              run: ./scripts/start-local-dendrite.sh --skip-postgres &

            - name: Start anvil
              run: anvil &

            - name: Deploy local zion governance contracts
              run: ./scripts/deploy-zion-governance-contracts.sh

            - name: Wait for dendrite to be ready
              run: yarn drt:wait

            - name: Unit Tests
              run: yarn test:unit

            - name: E2E Tests
              run: yarn test:dendrite:e2e

            # If CI failed, we send a slack notification
            - name: Slack notification
              if: failure() && (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch')
              uses: rtCamp/action-slack-notify@v2
              env:
                  SLACK_WEBHOOK: ${{ secrets.SLACK_CI_CHANNEL_WEBHOOK_URL }}
                  SLACK_TITLE: 'Failure'
                  SLACK_USERNAME: 'CI'
                  SLACK_ICON_EMOJI: ':boom:'
                  SLACK_COLOR: '#FF0000'
                  SLACK_MESSAGE: 'CI Failure on ${{ github.repository }}'

    Casablanca_Client_NoAuth:
        permissions: write-all
        if: github.event_name != 'workflow_dispatch' || !inputs.skip_casablanca_client_noauth
        runs-on: ubuntu-latest-8-cores
        timeout-minutes: 30
        services:
            postgres-casablanca:
                image: postgres:latest
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                ports:
                    # Maps tcp port 5433 on service container to the host
                    - 5433:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                    --name casablanca_postgres_container

        steps:
            - name: Cancel previous runs
              if: github.event_name != 'schedule'
              uses: styfle/cancel-workflow-action@0.11.0
              with:
                  access_token: ${{ github.token }}

            - name: Show PostgreSQL max_connections
              run: psql -h localhost -p 5433 -U postgres -c 'SHOW max_connections;'
              env:
                  POSTGRES_PASSWORD: postgres
                  PGPASSWORD: postgres

            - name: Increase max_connections in Postgres
              run: |
                  docker exec -i casablanca_postgres_container bash << EOF
                    echo 'max_connections = 1000' >> /var/lib/postgresql/data/postgresql.conf
                    echo 'shared_buffers = 2GB' >> /var/lib/postgresql/data/postgresql.conf
                  EOF
                  docker restart --time 0 casablanca_postgres_container
                  sleep 5

            - name: Show PostgreSQL max_connections
              run: psql -h localhost -p 5433 -U postgres -c 'SHOW max_connections;'
              env:
                  POSTGRES_PASSWORD: postgres
                  PGPASSWORD: postgres

            - name: Checkout code
              uses: actions/checkout@v3

            - name: Git submodules
              run: git submodule update --init --recursive

            - name: Setup Go
              uses: actions/setup-go@v3
              with:
                  go-version: '1.20'
                  cache: true
                  cache-dependency-path: |
                      servers/**/go.sum
                      casablanca/node/go.sum

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1
              with:
                  version: nightly

            - name: Install Forge modules
              run: ./scripts/install-deps.sh

            - uses: actions/setup-node@v3
              with:
                  node-version: '20'
                  cache: 'yarn'

            - name: Print versions
              run: ./scripts/print-versions.sh

            - name: Install node dependencies
              run: yarn install --immutable

            - name: Print Yarn package versions
              run: yarn info --name-only --all

            - name: Maintain Turbo cache
              uses: actions/cache@v3
              with:
                  path: node_modules/.cache/turbo
                  key: ${{ runner.os }}-turbo-${{ github.run_id }}
                  restore-keys: |
                      ${{ runner.os }}-turbo-

            - name: Syncpack
              run: yarn syncpack:check

            - name: Build contract types
              run: ./scripts/build-contract-types.sh localhost --frozen

            - name: Start anvil
              run: anvil &

            - name: Deploy local zion governance contracts
              run: ./scripts/deploy-zion-governance-contracts.sh

            - name: Casablanca create db
              run: psql -h localhost -p 5433 -U postgres -f scripts/sql/create_db.sql
              working-directory: casablanca
              env:
                  POSTGRES_PASSWORD: postgres
                  PGPASSWORD: postgres

            - name: Run Casablanca node (without auth)
              run: yarn csb:start --config dev-no-auth.yaml &

            - name: Wait for Casablanca node to be up
              run: yarn csb:wait

            - name: Run SDK Tests (without auth)
              run: yarn run turbo run build test:ci --filter=@towns/sdk

            - name: Run Node Flush Tests (without auth)
              run: yarn workspace @towns/sdk run test:node-minipool-flush

            - name: Archive Casablanca log
              if: always()
              uses: actions/upload-artifact@v3
              with:
                  name: casablanca-node-log
                  path: |
                      casablanca/node/logs/dev.log

            # If CI failed, we send a slack notification
            - name: Slack notification
              if: failure() && (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch')
              uses: rtCamp/action-slack-notify@v2
              env:
                  SLACK_WEBHOOK: ${{ secrets.SLACK_CI_CHANNEL_WEBHOOK_URL }}
                  SLACK_TITLE: 'Failure'
                  SLACK_USERNAME: 'CI'
                  SLACK_ICON_EMOJI: ':boom:'
                  SLACK_COLOR: '#FF0000'
                  SLACK_MESSAGE: 'CI Failure on ${{ github.repository }}'

    Casablanca_Client_Auth:
        permissions: write-all
        if: github.event_name != 'workflow_dispatch' || !inputs.skip_casablanca_client_auth
        runs-on: ubuntu-latest-8-cores
        timeout-minutes: 30
        services:
            postgres-casablanca:
                image: postgres:latest
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                ports:
                    # Maps tcp port 5433 on service container to the host
                    - 5433:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                    --name casablanca_postgres_container

        steps:
            - name: Cancel previous runs
              if: github.event_name != 'schedule'
              uses: styfle/cancel-workflow-action@0.11.0
              with:
                  access_token: ${{ github.token }}

            - name: Show PostgreSQL max_connections
              run: psql -h localhost -p 5433 -U postgres -c 'SHOW max_connections;'
              env:
                  POSTGRES_PASSWORD: postgres
                  PGPASSWORD: postgres

            - name: Increase max_connections in Postgres
              run: |
                  docker exec -i casablanca_postgres_container bash << EOF
                    echo 'max_connections = 1000' >> /var/lib/postgresql/data/postgresql.conf
                    echo 'shared_buffers = 2GB' >> /var/lib/postgresql/data/postgresql.conf
                  EOF
                  docker restart --time 0 casablanca_postgres_container
                  sleep 5

            - name: Show PostgreSQL max_connections
              run: psql -h localhost -p 5433 -U postgres -c 'SHOW max_connections;'
              env:
                  POSTGRES_PASSWORD: postgres
                  PGPASSWORD: postgres

            - name: Checkout code
              uses: actions/checkout@v3

            - name: Git submodules
              run: git submodule update --init --recursive

            - name: Setup Go
              uses: actions/setup-go@v3
              with:
                  go-version: '1.20'
                  cache: true
                  cache-dependency-path: |
                      servers/**/go.sum
                      casablanca/node/go.sum

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1
              with:
                  version: nightly

            - name: Install Forge modules
              run: ./scripts/install-deps.sh

            - uses: actions/setup-node@v3
              with:
                  node-version: '18.13.0'
                  cache: 'yarn'

            - name: Print versions
              run: ./scripts/print-versions.sh

            - name: Install node dependencies
              run: yarn install --immutable

            - name: Print Yarn package versions
              run: yarn info --name-only --all

            - name: Maintain Turbo cache
              uses: actions/cache@v3
              with:
                  path: node_modules/.cache/turbo
                  key: ${{ runner.os }}-turbo-${{ github.run_id }}
                  restore-keys: |
                      ${{ runner.os }}-turbo-

            - name: Syncpack
              run: yarn syncpack:check

            - name: Build contract types
              run: ./scripts/build-contract-types.sh localhost --frozen

            - name: Start anvil
              run: anvil &

            - name: Deploy local zion governance contracts
              run: ./scripts/deploy-zion-governance-contracts.sh

            - name: Casablanca create db
              run: psql -h localhost -p 5433 -U postgres -f scripts/sql/create_db.sql
              working-directory: casablanca
              env:
                  POSTGRES_PASSWORD: postgres
                  PGPASSWORD: postgres

            - name: Start Casablanca node with auth
              run: yarn csb:start --config dev-auth.yaml &

            - name: Wait for Casablanca (with auth) node to be up
              run: yarn csb:wait

            - name: Build & Test (with auth)
              run: yarn csb:turbo-no-sdk

            - name: Archive Casablanca log
              if: always()
              uses: actions/upload-artifact@v3
              with:
                  name: casablanca-node-log
                  path: |
                      casablanca/node/logs/dev.log

            # If CI failed, we send a slack notification
            - name: Slack notification
              if: failure() && (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch')
              uses: rtCamp/action-slack-notify@v2
              env:
                  SLACK_WEBHOOK: ${{ secrets.SLACK_CI_CHANNEL_WEBHOOK_URL }}
                  SLACK_TITLE: 'Failure'
                  SLACK_USERNAME: 'CI'
                  SLACK_ICON_EMOJI: ':boom:'
                  SLACK_COLOR: '#FF0000'
                  SLACK_MESSAGE: 'CI Failure on ${{ github.repository }}'

    Casablanca_Node:
        permissions: write-all
        if: github.event_name != 'workflow_dispatch' || !inputs.skip_casablanca_node
        runs-on: ubuntu-latest-8-cores
        timeout-minutes: 30
        services:
            postgres-casablanca:
                image: postgres:latest
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                ports:
                    # Maps tcp port 5433 on service container to the host
                    - 5433:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        steps:
            - name: Cancel previous runs
              if: github.event_name != 'schedule'
              uses: styfle/cancel-workflow-action@0.11.0
              with:
                  access_token: ${{ github.token }}

            - name: Checkout code
              uses: actions/checkout@v3

            - name: Git submodules
              run: git submodule update --init --recursive

            - name: Setup Go
              uses: actions/setup-go@v3
              with:
                  go-version: '1.20'
                  cache: true
                  cache-dependency-path: |
                      casablanca/node/go.sum

            - name: Linting
              uses: golangci/golangci-lint-action@v3
              with:
                  working-directory: casablanca/node

            - name: Casablanca create db
              run: psql -h localhost -p 5433 -U postgres -f scripts/sql/create_db.sql
              working-directory: casablanca
              env:
                  POSTGRES_PASSWORD: postgres
                  PGPASSWORD: postgres

            - name: Run node tests
              run: go test --race ./...
              working-directory: casablanca/node

            # If CI failed, we send a slack notification
            - name: Slack notification
              if: failure() && (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch')
              uses: rtCamp/action-slack-notify@v2
              env:
                  SLACK_WEBHOOK: ${{ secrets.SLACK_CI_CHANNEL_WEBHOOK_URL }}
                  SLACK_TITLE: 'Failure'
                  SLACK_USERNAME: 'CI'
                  SLACK_ICON_EMOJI: ':boom:'
                  SLACK_COLOR: '#FF0000'
                  SLACK_MESSAGE: 'CI Failure on ${{ github.repository }}'
