name: Continuous Integration
on:
    push:
        branches:
            - main
    pull_request:

jobs:
    check:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        services:
            redis:
                image: redis:latest
                options: >-
                    --health-cmd "redis-cli ping"
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                    - 55000:6379
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Cancel previous runs
              uses: styfle/cancel-workflow-action@0.11.0
              with:
                  access_token: ${{ github.token }}

            - name: Cache node modules
              uses: actions/cache@v3
              env:
                  cache-name: cache-node-modules
              with:
                  path: |
                      node_modules
                  key: yarn-lock-${{ hashFiles('yarn.lock') }}

            - uses: actions/setup-node@v3
              with:
                  node-version: '18'
                  cache: 'yarn'
            - run: yarn install --immutable
            - run: yarn lint
            - run: yarn prettier:check
            - run: yarn syncpack:check
            - run: yarn csb:build
            - run: yarn csb:test
