name: Comment Transient Environment
on:
    pull_request:
        types: [opened, ready_for_review]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: false

jobs:
    comment_transient_environment:
        permissions: write-all
        runs-on: ubuntu-latest-8-cores
        timeout-minutes: 20

        env:
            GIT_PR_NUMBER: ${{ github.event.pull_request.number }}

        steps:
            - name: Comment on PR
              uses: actions/github-script@v6
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  script: |
                      const gitPrNumber = process.env.GIT_PR_NUMBER;
                      const webAppUrl = `https://${gitPrNumber}.app-preview.towns.com`;
                      const sampleAppUrl = `https://${gitPrNumber}.sample-app-preview.towns.com`;
                      const riverNodeUrl = `https://river1-transient-${gitPrNumber}.towns.com`;
                      const message = `
                      Web App: [${webAppUrl}](${webAppUrl})
                      Sample App: [${sampleAppUrl}](${sampleAppUrl})
                      River Node: [${riverNodeUrl}](${riverNodeUrl})
                      `;

                      github.rest.issues.createComment({
                          issue_number: context.issue.number,
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          body: message
                      })

            - name: Slack notification
              if: failure()
              uses: slackapi/slack-github-action@v1.24.0
              with:
                  payload: |
                      {
                          "step": "Comment Transient Environment",
                          "environment": "Transient-${{ github.event.pull_request.number }}",
                          "branch": "${{ github.ref }}",
                          "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                          "commit": "${{ github.sha }}",
                          "actor": "${{ github.actor }}"
                      }
              env:
                  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_CD_WORKFLOW_WEBHOOK_URL }}
