name: 'Dendrite_deploy'

on:
    workflow_call:
        inputs:
            task_definition:
                description: 'Task definition'
                type: string
                required: true
            service:
                description: 'Service name to deploy to'
                type: string
                required: true
            cluster:
                description: 'Cluster name to deploy to'
                type: string
                required: true

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    deploy:
        name: Deploy to AWS ECS
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1

            - name: Redeploy service
              run: |
                  aws ecs update-service --cluster=${{ inputs.cluster }} --service=${{ inputs.service }} --task-definition=${{ inputs.task_definition }} --force-new-deployment

            - name: Wait for service to be stable
              run: |
                  aws ecs wait services-stable --cluster=${{ inputs.cluster }} --services=${{ inputs.service }}
