# Based on https://github.com/docker/build-push-action

name: 'Build HNT Infra Docker Image'

on:
    push:
        branches:
            - main
        paths:
            - 'infra/**'
    workflow_dispatch:

env:
    DOCKER_NAMESPACE: herenotthere
    GHCR_NAMESPACE: herenotthere
    PLATFORMS: linux/amd64,linux/arm64
    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_CD_WORKFLOW_WEBHOOK_URL }}

jobs:
    build:
        name: Build docker image

        runs-on: ubuntu-latest-8-cores

        permissions:
            contents: write
            packages: write

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-east-1

            - name: Login to Amazon ECR
              id: login-aws-ecr
              uses: aws-actions/amazon-ecr-login@v2

            - name: Build and push infra image to Amazon ECR
              env:
                ECR_REGISTRY: ${{ steps.login-aws-ecr.outputs.registry }}
                ECR_REPOSITORY: hnt-infra
              run: |
                cd ./infra
                docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
                docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

            # If action failed, we send a slack notification
            - name: Slack notification
              if: failure()
              uses: slackapi/slack-github-action@v1.24.0
              with:
                  payload: |
                      {
                          "step": "Build Infra Docker Image",
                          "environment": "N/",
                          "branch": "${{ github.ref }}",
                          "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                          "commit": "${{ github.sha }}",
                          "actor": "${{ github.actor }}"
                      }
