name: 'Build River Metrics Discovery Docker Image'

on:
    push:
        branches:
            - main
        paths:
            - '.github/workflows/Metrics_discovery_docker.yml'
            - '.github/workflows/_build-docker-arch.yml'
            - 'packages/metrics-discovery/**'
            - 'packages/web3/**'
    workflow_dispatch:

env:
    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_CD_WORKFLOW_WEBHOOK_URL }}

jobs:
    build:
        name: Build docker image
        uses: ./.github/workflows/_build-docker-arch.yml
        with:
            architecture: amd64
            platform: linux/amd64
            runner: ubuntu-latest
            ecr_registry_alias: h5v6m2x1
            ecr_repository: river-metrics-discovery
            dockerfile: ./packages/metrics-discovery/Dockerfile
            cache_scope_prefix: metrics-discovery
        secrets: inherit

    # Slack notification on failure
    notify-failure:
        name: Notify on failure
        if: failure()
        needs: [build]
        runs-on: ubuntu-latest
        steps:
            - name: Slack notification
              uses: slackapi/slack-github-action@v1.24.0
              with:
                  payload: |
                      {
                          "step": "Build Metrics Discovery Docker Image",
                          "environment": "N/A",
                          "branch": "${{ github.ref }}",
                          "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                          "commit": "${{ github.sha }}",
                          "actor": "${{ github.actor }}"
                      }
