name: Create PR for Omega Release

on:
    workflow_dispatch:
    schedule:
        # Run every Thursday at 9:00 AM PT (16:00 UTC)
        - cron: '0 16 * * 4'

jobs:
    create-pr:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
              with:
                  ref: ${{ github.ref }}
                  fetch-depth: 0
                  persist-credentials: false

            - name: Get Current Date
              id: date
              run: echo "DATE=$(date +'%m-%d-%Y')" >> $GITHUB_ENV

            - name: Get Latest Commit SHA
              id: sha
              run: |
                  if [[ "${{ github.event_name }}" == "schedule" ]]; then
                    LATEST_RC_TAG=$(git describe --tags --abbrev=0 --match "rc-*")
                    echo "COMMIT_SHA=$(git rev-list -n 1 $LATEST_RC_TAG)" >> $GITHUB_ENV
                  else
                    echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
                  fi

            - name: Set Branch Name
              run: echo "RELEASE_BRANCH=omega-release/${{ env.DATE }}-${{ env.COMMIT_SHA }}" >> $GITHUB_ENV

            - name: Authenticate Github with PAT
              run: |
                  git remote set-url origin https://${{ secrets.HARMONY_GITHUB_PAT }}@github.com/HereNotThere/harmony.git

            - name: Create Release Branch
              env:
                  GITHUB_TOKEN: ${{ secrets.HARMONY_GITHUB_PAT }}
              run: |
                  git fetch origin
                  git checkout -b ${{ env.RELEASE_BRANCH }}
                  git rebase origin/omega
                  git push -u origin ${{ env.RELEASE_BRANCH }}

            - name: Create Pull Request using GitHub CLI
              env:
                  GITHUB_TOKEN: ${{ secrets.HARMONY_GITHUB_PAT }}
              run: |
                  gh pr create --title "Omega Release" --body "Latest omega app release.\n\nCommit SHA: ${{ env.COMMIT_SHA }}" --head ${{ env.RELEASE_BRANCH }} --base omega
