name: Pull River

on:
    workflow_dispatch:

jobs:
    Common_CI:
        permissions: write-all
        runs-on: ['arc-runners']
        timeout-minutes: 30

        steps:
            - name: Print bash environment
              run: env

            - name: Cancel previous runs
              if: github.event_name != 'schedule'
              uses: styfle/cancel-workflow-action@0.12.1
              with:
                  access_token: ${{ github.token }}

            - name: Checkout code
              uses: actions/checkout@v4

            - name: Test
              run: echo "Test"
