name: Tag Release Candidate

on:
    schedule:
        - cron: '0 0 * * *' # Runs every day at midnight UTC

    workflow_dispatch:

jobs:
    tag_rc:
        name: Tag Release Candidate
        runs-on: ubuntu-latest

        permissions:
            contents: write
            pull-requests: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Get current date
              run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

            - name: Create and push tag
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  DATE: ${{ env.DATE }}
              run: |
                  TAG_NAME="rc-$DATE"
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"
                  git tag $TAG_NAME
                  git push origin $TAG_NAME

            # If action failed, we send a slack notification
            - name: Slack notification
              if: failure()
              uses: slackapi/slack-github-action@v1.24.0
              env:
                  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_CD_WORKFLOW_WEBHOOK_URL }}
              with:
                  payload: |
                      {
                          "step": "Release Candidate Tag",
                          "environment": "Alpha",
                          "branch": "${{ github.ref }}",
                          "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                          "commit": "${{ github.sha }}",
                          "actor": "${{ github.actor }}"
                      }
