name: Release
on:
    push:
        branches:
            - main
            - 'ci/**'
jobs:
    release:
        permissions: write-all
        runs-on: ubuntu-latest-8-cores
        timeout-minutes: 30
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Cancel previous runs
              uses: styfle/cancel-workflow-action@0.11.0
              with:
                  access_token: ${{ github.token }}

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1
              with:
                  version: nightly

            - name: Install Forge modules
              run: ./scripts/install-deps.sh

            - uses: actions/setup-node@v3
              with:
                  node-version: '20'
                  cache: 'yarn'

            - name: Install node dependencies
              run: yarn install --immutable

            - name: Maintain Turbo cache
              uses: actions/cache@v3
              with:
                  path: node_modules/.cache/turbo
                  key: ${{ runner.os }}-turbo-${{ github.run_id }}
                  restore-keys: |
                      ${{ runner.os }}-turbo-

            - name: Build
              run: yarn build

            # If CI failed, we send a slack notification
            - name: Slack notification
              if: failure()
              uses: rtCamp/action-slack-notify@v2
              env:
                  SLACK_WEBHOOK: ${{ secrets.SLACK_CI_CHANNEL_WEBHOOK_URL }}
                  SLACK_TITLE: 'Failure'
                  SLACK_USERNAME: 'CI'
                  SLACK_ICON_EMOJI: ':boom:'
                  SLACK_COLOR: '#FF0000'
                  SLACK_MESSAGE: 'Release Failure on ${{ github.repository }}'
