# Based on https://github.com/docker/build-push-action

name: 'Build River Stress Test Node Docker Image'

on:
    push:
        branches:
            - main
        paths:
            - '.github/workflows/Stress_test_node_docker.yml'
            - '.github/workflows/_build-docker-arch.yml'
            - 'packages/**'
    workflow_dispatch:

env:
    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_CD_WORKFLOW_WEBHOOK_URL }}

jobs:
    build:
        name: Build docker image
        uses: ./.github/workflows/_build-docker-arch.yml
        with:
            architecture: amd64
            platform: linux/amd64
            runner: ubuntu-latest
            ecr_registry_alias: h5v6m2x1
            ecr_repository: river-stress-test-node
            dockerfile: ./packages/stress-testing/Dockerfile
            cache_scope_prefix: stress-testing
        secrets: inherit

    # Slack notification on failure
    notify-failure:
        name: Notify on failure
        if: failure()
        needs: [build]
        runs-on: ubuntu-latest
        steps:
            - name: Slack notification
              uses: slackapi/slack-github-action@v1.24.0
              with:
                  payload: |
                      {
                          "step": "Build Stress Test Node Docker Image",
                          "environment": "N/A",
                          "branch": "${{ github.ref }}",
                          "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                          "commit": "${{ github.sha }}",
                          "actor": "${{ github.actor }}"
                      }
