# Based on https://github.com/docker/build-push-action

name: 'Deploy Stream Metadata Service'

on:
    push:
        branches:
            - main
        paths:
            - 'river/packages/stream-metadata/**'

    workflow_dispatch:
        inputs:
            environment_name:
                description: 'Environment name'
                required: true
                type: choice
                options:
                    - 'gamma'
                    - 'omega'
                    - 'alpha'
                default: 'gamma'

    workflow_call:
        inputs:
            environment_name:
                description: 'Environment name'
                required: true
                type: string
        secrets:
            AWS_ACCESS_KEY_ID:
                description: 'AWS access key id'
                required: true
            AWS_SECRET_ACCESS_KEY:
                description: 'AWS secret access key'
                required: true
            SLACK_CD_ALERT_WORKFLOW_WEBHOOK_URL:
                description: 'Slack webhook url for alerting'
                required: true
            SLACK_CD_INFO_WORKFLOW_WEBHOOK_URL:
                description: 'Slack webhook url for info'
                required: true

env:
    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_CD_ALERT_WORKFLOW_WEBHOOK_URL }}

concurrency:
    group: stream-metadata-service-${{ github.ref }}-${{ inputs.environment_name }}
    cancel-in-progress: true

jobs:
    build:
        name: Deploy Latest Docker Image

        runs-on: ubuntu-latest

        steps:
            - name: Set Environment Variables
              env:
                  BRANCH_NAME: ${{ github.ref }}
                  ENVIRONMENT_NAME_INPUT: ${{ inputs.environment_name }}
              run: |
                  if [ -n "$ENVIRONMENT_NAME_INPUT" ]; then
                    echo "ENV_NAME=$ENVIRONMENT_NAME_INPUT" >> $GITHUB_ENV
                  elif [ $BRANCH_NAME = "refs/heads/main" ]; then
                    echo "ENV_NAME=gamma" >> $GITHUB_ENV
                  else
                    echo "Error: Branch name is not main or omega. Exiting."
                    exit 1
                  fi

            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1

            - name: Deploy to ECS
              run: './scripts/deploy-latest-stream-metadata-service.sh'
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_REGION: us-east-1
                  ENVIRONMENT_NAME: ${{ env.ENV_NAME }}

            # If action failed, we send a slack notification
            - name: Slack notification
              if: failure()
              uses: slackapi/slack-github-action@v1.24.0
              with:
                  payload: |
                      {
                          "step": "Deploy Stream Metadata",
                          "environment": "N/A",
                          "branch": "${{ github.ref }}",
                          "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                          "commit": "${{ github.sha }}",
                          "actor": "${{ github.actor }}"
                      }
