name: 'Run Synthetic Transactions'
env:
    FOUNDRY_VERSION: nightly

on:
    workflow_dispatch: # A synthetic test which is triggered each 30 minutes
        inputs:
            environment_name:
                description: 'Environment Name'
                type: string
                default: 'gamma'
    workflow_call:
        inputs:
            environment_name:
                description: 'Environment Name'
                type: string
        secrets:
            SLACK_CI_CHANNEL_WEBHOOK_URL: { required: true }
    schedule: # A synthetic test was scheduled
        - cron: '*/1 * * * *' # Every 1 minute
jobs:
    run_synthetic_tests:
        runs-on:
          group: synthetic-test-runners

        timeout-minutes: 240
        services:
            redis:
                image: redis:latest
                ports:
                    - '6379:6379'

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Git submodules
              run: git submodule update --init --recursive

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1
              with:
                  version: ${{ env.FOUNDRY_VERSION }}

            - name: Install Forge modules
              run: ./scripts/install-deps.sh

            - uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'yarn'

            - name: Install node dependencies
              run: yarn install --immutable

            - name: Build town types
              working-directory: river
              run: ./scripts/build-contract-types.sh localhost --frozen


            - name: Setup River CA for testing certificates
              run: ./scripts/register-ca.sh
              working-directory: river/core

            - name: Set up Custom CA Certificate for Node.js
              run: |
                echo "NODE_EXTRA_CA_CERTS=$HOME/river-ca-cert.pem" >> $GITHUB_ENV

            - name: Run Synthetic Test
              run: yarn test:ci:synthetic:all
              working-directory: river
              env:
                  ENVIRONMENT_NAME: ${{inputs.environment_name || 'gamma' }}
                  DEBUG: csb:test:synthetic

            # If failed, we send a slack notification
            - name: Slack notification
              if: failure()
              uses: rtCamp/action-slack-notify@v2
              env:
                  SLACK_MESSAGE_FOR_MAIN: 'Synthetic Test Failure <@${{ env.TESTS_GOALIE_SLACK_GROUP_ID }}>'
                  SLACK_MESSAGE_FOR_TRANSIENT: 'Synthetic Test Failure'

                  SLACK_WEBHOOK: ${{ secrets.SLACK_CI_CHANNEL_WEBHOOK_URL }}
                  SLACK_TITLE: 'Failure'
                  SLACK_USERNAME: 'Synthetic Tests'
                  SLACK_ICON_EMOJI: ':test_tube:'
                  SLACK_COLOR: '#FF0000'
                  SLACK_MESSAGE: ${{ inputs.environment_name == 'gamma' && env.SLACK_MESSAGE_FOR_MAIN || env.SLACK_MESSAGE_FOR_TRANSIENT}}
