name: 'Run Synthetic Transactions'
env:
    FOUNDRY_VERSION: nightly

on:
    workflow_dispatch: # A synthetic test which is triggered each 30 minutes
        inputs:
            environment_name:
                description: 'Environment Name'
                type: string
                default: 'test-beta'
    workflow_call:
        inputs:
            environment_name:
                description: 'Environment Name'
                type: string
        secrets:
            SLACK_CI_CHANNEL_WEBHOOK_URL: { required: true }
    schedule: # A synthetic test was scheduled
        - cron: '*/1 * * * *' # Every 1 minute
jobs:
    run_synthetic_tests:
        runs-on:
          group: synthetic-test-runners
        
        timeout-minutes: 240
        services:
            redis:
                image: redis:latest
                ports:
                    - '6379:6379'

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Git submodules
              run: git submodule update --init --recursive

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1
              with:
                  version: ${{ env.FOUNDRY_VERSION }}

            - name: Install Forge modules
              run: ./scripts/install-deps.sh

            - uses: actions/setup-node@v3
              with:
                  node-version: '18.13.0'
                  cache: 'yarn'

            - name: Install node dependencies
              run: yarn install --immutable

            - name: Build town types
              run: ./scripts/build-town-types.sh localhost --frozen

            - name: Run Synthetic Test
              run: yarn test:ci:synthetic:all
              env:
                  ENVIRONMENT_NAME: ${{inputs.environment_name || 'test-beta' }} #river1-transient-{0}.towns.com

            # If failed, we send a slack notification
            - name: Slack notification
              if: failure()
              uses: rtCamp/action-slack-notify@v2
              env:
                  SLACK_MESSAGE_FOR_MAIN: 'Synthetic Test Failure <@${{ env.TESTS_GOALIE_SLACK_GROUP_ID }}>'
                  SLACK_MESSAGE_FOR_TRANSIENT: 'Synthetic Test Failure'

                  SLACK_WEBHOOK: ${{ secrets.SLACK_CI_CHANNEL_WEBHOOK_URL }}
                  SLACK_TITLE: 'Failure'
                  SLACK_USERNAME: 'Synthetic Tests'
                  SLACK_ICON_EMOJI: ':test_tube:'
                  SLACK_COLOR: '#FF0000'
                  SLACK_MESSAGE: ${{ inputs.environment_name == 'test-beta' && env.SLACK_MESSAGE_FOR_MAIN || env.SLACK_MESSAGE_FOR_TRANSIENT}}
