# Based on https://github.com/docker/build-push-action

name: 'Towns_node_docker'

on:
    push:
        branches:
            - main
        paths:
            - 'casablanca/node/**'
    workflow_dispatch: # A build was manually requested
    workflow_call: # Another pipeline called us
        secrets:
            DOCKER_HUB_TOKEN:
                required: true
            DOCKER_HUB_USERNAME:
                required: true

env:
    DOCKER_NAMESPACE: herenotthere
    GHCR_NAMESPACE: herenotthere
    PLATFORMS: linux/amd64,linux/arm64

jobs:
    monolith:
        name: Build docker image
        runs-on: ubuntu-latest-8-cores
        permissions:
            contents: write
            packages: write
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Put commit hash to release version
              working-directory: ./scripts
              run: bash echo-commit-hash.sh | awk '{print "RELEASE_VERSION="$1""}' >> $GITHUB_ENV

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_TOKEN }}

            - name: Build towns
              uses: docker/build-push-action@v4
              with:
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
                  context: ./casablanca/node
                  file: ./casablanca/node/Dockerfile
                  platforms: ${{ env.PLATFORMS }}
                  push: true
                  build-args: |
                      RELEASE_VERSION=${{ env.RELEASE_VERSION }}
                  tags: |
                      ${{ env.DOCKER_NAMESPACE }}/towns-node:latest
                      ${{ env.DOCKER_NAMESPACE }}/towns-node:${{ env.RELEASE_VERSION }}

            # If action failed, we send a slack notification
            - name: Slack notification
              if: failure()
              uses: rtCamp/action-slack-notify@v2
              env:
                  SLACK_WEBHOOK: ${{ secrets.SLACK_CI_CHANNEL_WEBHOOK_URL }}
                  SLACK_TITLE: 'Failure'
                  SLACK_USERNAME: 'CI'
                  SLACK_ICON_EMOJI: ':boom:'
                  SLACK_COLOR: '#FF0000'
                  SLACK_MESSAGE: 'Towns Node Docker Failed on ${{ github.repository }}'
