name: Upgrade Alpha Facets
env:
    FOUNDRY_VERSION: nightly
    ALPHA_BASE_SEPOLIA_DEPLOYER_PK: ${{ secrets.ALPHA_BASE_SEPOLIA_DEPLOYER_PK }}
    BASE_SEPOLIA_RPC_URL: ${{ secrets.ALPHA_BASE_SEPOLIA_RPC_URL }}
    RIVER_RPC_URL: ${{ secrets.RIVER_TESTNET_RPC_URL }}
    BLOCKSCOUT_SEPOLIA_API_KEY: ${{ secrets.BLOCKSCOUT_BASE_SEPOLIA_API_KEY }}
    RIVERSCAN_DEVNET_API_KEY: 'PLACEHOLDER_STRING'
    RIVERSCAN_API_KEY: 'PLACEHOLDER_STRING'
    BLOCKSCOUT_BASE_URL: 'https://base.blockscout.com/api'
    BLOCKSCOUT_SEPOLIA_URL: 'https://base-sepolia.blockscout.com/api'
    BLOCKSCOUT_BASE_API_KEY: ${{ secrets.BLOCKSCOUT_BASE_SEPOLIA_API_KEY }}
    BASESCAN_SEPOLIA_URL: 'https://api-sepolia.basescan.org/api'
    BASESCAN_SEPOLIA_API_KEY: ${{ secrets.BASESCAN_SEPOLIA_API_KEY }}
    RIVERSCAN_DEVNET_URL: 'https://towns-devnet.explorer.caldera.xyz/api'
    RIVER_DEVNET_RPC_URL: 'https://towns-devnet.rpc.caldera.xyz/http'

on:
    workflow_dispatch: # Allows manual triggering

    workflow_call:
        secrets:
            ALPHA_BASE_SEPOLIA_DEPLOYER_PK:
                required: true
            SLACK_CD_ALERT_WORKFLOW_WEBHOOK_URL:
                required: true
            ALPHA_BASE_SEPOLIA_RPC_URL:
                required: true
            RIVER_TESTNET_RPC_URL:
                required: true
            BLOCKSCOUT_BASE_SEPOLIA_API_KEY:
                required: true
            BASESCAN_SEPOLIA_API_KEY:
                required: true
jobs:
    Upgrade_Facets:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  ref: main

            - uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'yarn'

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1
              with:
                  version: ${{ env.FOUNDRY_VERSION }}

            - name: Install node dependencies
              run: yarn install --immutable

            - name: Run Base Sepolia Interaction
              run: make interact-any-explicit \
                  context=alpha \
                  rpc=base_sepolia \
                  contract=InteractAlpha \
                  private_key=${{ env.ALPHA_BASE_SEPOLIA_DEPLOYER_PK }} \
                  etherscan=${{ env.BLOCKSCOUT_SEPOLIA_API_KEY }} \
                  verifier=${{ env.BLOCKSCOUT_SEPOLIA_URL }}
              working-directory: river/contracts

            # - name: Verify Base Sepolia Interaction
            #   run: make interact-resume-any-explicit \
            #       context=alpha \
            #       rpc=base_sepolia \
            #       contract=InteractAlpha \
            #       private_key=${{ env.ALPHA_BASE_SEPOLIA_DEPLOYER_PK }} \
            #       etherscan=${{ env.BASESCAN_SEPOLIA_API_KEY }} \
            #       verifier=${{ env.BASESCAN_SEPOLIA_URL }}
            #   working-directory: river/contracts

            - name: Run River Devnet Interaction
              env:
                  ETHERSCAN_API_KEY: ${{ env.RIVERSCAN_DEVNET_API_KEY }}
              run: make interact-any-explicit-blockscout \
                  context=alpha \
                  rpc=river_devnet \
                  contract=InteractRiverAlpha \
                  private_key=${{ env.ALPHA_BASE_SEPOLIA_DEPLOYER_PK }} \
                  verifier=${{ env.RIVERSCAN_DEVNET_URL }}
              working-directory: river/contracts

            # If action failed, we send a slack notification
            - name: Slack notification
              if: failure()
              uses: slackapi/slack-github-action@v1.24.0
              env:
                  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_CD_ALERT_WORKFLOW_WEBHOOK_URL }}
              with:
                  payload: |
                      {
                          "step": "Upgrade Alpha Facets",
                          "environment": "alpha",
                          "branch": "${{ github.ref }}",
                          "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                          "commit": "${{ github.sha }}",
                          "actor": "${{ github.actor }}"
                      }
