name: 'Run Userops Tests'
env:
    FOUNDRY_VERSION: nightly
    RIVER_BLOCK_TIME: 1
    BASE_EXECUTION_CLIENT: geth_dev

on:
    pull_request:
        paths:
            - 'river/**'
            - 'servers/4337/**'
            - 'servers/workers/worker-common/**'
            - 'servers/workers/stackup-worker/**'
            - 'clients/web/userops/**'
    workflow_dispatch: # Allow manual trigger in GitHub UI

jobs:
    user_ops_tests:
        runs-on: ubuntu-latest-8-cores
        timeout-minutes: 240
        steps:
            - uses: taiki-e/install-action@just

            - name: Checkout code
              uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'yarn'

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: '1.22'

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1
              with:
                  version: ${{ env.FOUNDRY_VERSION }}

            - name: Install node dependencies
              run: yarn install --immutable

            - name: Build workers
              run: yarn workers:build

            - name: Start 4337
              env:
                  STACKUP_CONTRACTS_GIT_TOKEN: ${{ secrets.STACKUP_CONTRACTS_GIT_TOKEN }}
              run: ./scripts/start-4337.sh &

            - name: Wait for 4337
              timeout-minutes: 10
              run: ./scripts/wait-for-4337.sh

            - name: Start River blockchain
              run: ./river/scripts/start-local-riverchain.sh &

            - name: Setup River CA for testing certificates
              run: ./scripts/register-ca.sh
              working-directory: river/core

            - name: Set up Custom CA Certificate for Node.js
              run: |
                  echo "NODE_EXTRA_CA_CERTS=$HOME/river-ca-cert.pem" >> $GITHUB_ENV

            - name: Configure multi
              run: just RUN_ENV=multi config
              working-directory: river/core

            - name: Spin up stackup worker with fake privy verification that skips limit checks
              working-directory: ./servers/workers/stackup-worker
              run: PORT=8787 yarn dev:local --var ERC4337_ENTRYPOINT_ADDRESS:0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789 SKIP_LIMIT_VERIFICATION:true SKIP_PRIVY_VERIFICATION:true STACKUP_PAYMASTER_RPC_URL:http://localhost:43371 PRIVY_APP_KEY:${{ secrets.PRIVY_APP_KEY }} PRIVY_APP_ID:clml5fp7s013vmf0fnkabuaiw ALCHEMY_API_KEY:FAKE AUTH_SECRET:foo ENVIRONMENT:development &

            - name: Spin up stackup worker with fake privy verification and strict limits
              working-directory: ./servers/workers/stackup-worker
              run: PORT=8989 yarn dev:local --var LIMIT_CREATE_SPACE:1 LIMIT_ROLE_SET:1 LIMIT_ENTITLEMENT_SET:1 LIMIT_CHANNEL_CREATE:1 LIMIT_LINK_WALLET:1 LIMIT_UPDATE_SPACE_INFO:1 LIMIT_BAN_UNBAN:1 SKIP_PRIVY_VERIFICATION:true ERC4337_ENTRYPOINT_ADDRESS:0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789 STACKUP_PAYMASTER_RPC_URL:http://localhost:43371 PRIVY_APP_KEY:${{ secrets.PRIVY_APP_KEY }} PRIVY_APP_ID:clml5fp7s013vmf0fnkabuaiw ALCHEMY_API_KEY:FAKE AUTH_SECRET:foo ENVIRONMENT:development &

            - name: Wait for second stackup worker with privy checks to be up on 8787
              run: PORT=8787 yarn worker:wait:stackup

            - name: Wait for stackup worker with limits enforced to be up on 8989
              run: PORT=8989 yarn worker:wait:stackup

            - name: Run @towns/userop package tests
              timeout-minutes: 10
              env:
                  AA_PAYMASTER_PROXY_URL: http://127.0.0.1:8787
                  AA_PAYMASTER_PROXY_AUTH_SECRET: Zm9v
                  AA_RPC_URL: http://localhost:8545
                  AA_BUNDLER_URL: http://localhost:43370
                  RIVER_ENV: local_multi

              working-directory: ./clients/web/userops
              run: yarn test:userops:random-wallet

            - name: Run @towns/userop package tests with max daily limits of 1
              timeout-minutes: 10
              env:
                  AA_PAYMASTER_PROXY_URL: http://127.0.0.1:8989
                  AA_PAYMASTER_PROXY_AUTH_SECRET: Zm9v
                  AA_RPC_URL: http://localhost:8545
                  AA_BUNDLER_URL: http://localhost:43370
                  RIVER_ENV: local_multi

              working-directory: ./clients/web/userops
              run: yarn test:userops:paymaster-limits

            - name: Run @towns/userop package tests against legacy spaces
              timeout-minutes: 10
              env:
                  AA_PAYMASTER_PROXY_URL: http://127.0.0.1:8787
                  AA_PAYMASTER_PROXY_AUTH_SECRET: Zm9v
                  AA_RPC_URL: http://localhost:8545
                  AA_BUNDLER_URL: http://localhost:43370
                  RIVER_ENV: local_multi
                  CREATE_LEGACY_SPACES: true

              working-directory: ./clients/web/userops
              run: yarn test:userops:random-wallet

            - name: Run @towns/userop package tests with max daily limits of 1 against legacy spaces
              timeout-minutes: 10
              env:
                  AA_PAYMASTER_PROXY_URL: http://127.0.0.1:8989
                  AA_PAYMASTER_PROXY_AUTH_SECRET: Zm9v
                  AA_RPC_URL: http://localhost:8545
                  AA_BUNDLER_URL: http://localhost:43370
                  RIVER_ENV: local_multi
                  CREATE_LEGACY_SPACES: true

              working-directory: ./clients/web/userops
              run: yarn test:userops:paymaster-limits

            - name: Stop 4337
              run: ./scripts/stop-4337.sh
