name: 'Run Userops Tests'
env:
    FOUNDRY_VERSION: nightly

on:
  workflow_dispatch:
  schedule:
      # Once per hour between 8 - 4 PST
      - cron: '0 16-23,0 * * *'

jobs:
    user_ops_tests:
        environment: gamma
        runs-on: ubuntu-latest-8-cores
        timeout-minutes: 240
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1
              with:
                  version: ${{ env.FOUNDRY_VERSION }}

            - uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'yarn'

            - name: Install node dependencies
              run: yarn install --immutable

            - name: Spin up stackup worker without verification
              working-directory: ./servers/workers/stackup-worker
              # PAYMASTER_ADDRESS is actually the entrypoint address and we need to change the name of this env var
              # https://linear.app/hnt-labs/issue/HNT-4569/change-paymaster-address-to-entrypoint-address-in-paymaster-proxy
              run: yarn dev:local --var PAYMASTER_ADDRESS:0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789 STACKUP_API_TOKEN:${{ secrets.STACKUP_TEST_API_TOKEN }} SKIP_TOWNID_VERIFICATION:true AUTH_SECRET:foo &

            - name: Spin up stackup worker with verification
              working-directory: ./servers/workers/stackup-worker
              # PAYMASTER_ADDRESS is actually the entrypoint address and we need to change the name of this env var
              # https://linear.app/hnt-labs/issue/HNT-4569/change-paymaster-address-to-entrypoint-address-in-paymaster-proxy
              run: PORT=8787 yarn dev:local --var PAYMASTER_ADDRESS:0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789 SKIP_LIMIT_VERIFICATION:true STACKUP_API_TOKEN:${{ secrets.STACKUP_TEST_API_TOKEN }} PRIVY_APP_KEY:${{ secrets.PRIVY_APP_KEY }} PRIVY_APP_ID:clml5fp7s013vmf0fnkabuaiw ALCHEMY_API_KEY:${{ secrets.ALCHEMY_API_KEY }} AUTH_SECRET:foo ENVIRONMENT:test-beta &

            - name: Wait for first stackup worker to be up on 8686
              run: yarn worker:wait:stackup

            - name: Wait for second stackup worker to be up on 8787
              run: PORT=8787 yarn worker:wait:stackup

            # #### Disabled b/c of error connecting to node
            # ConnectError: [failed_precondition] CreateStream: createStreamImpl: (62:DOWNSTREAM_NETWORK_ERROR) unavailable: URL "stream.river-testnet.nodes.unit410.com/river.NodeToNode/AllocateStream" missing scheme: use http:// or https:// (unlike grpc-go) 
            # 
            # - name: Run userop integration tests without verification (river/lib/base-sepolia)
            #   timeout-minutes: 15
            #   env:
            #     AA_PAYMASTER_PROXY_URL: http://127.0.0.1:8686
            #     AA_PAYMASTER_PROXY_AUTH_SECRET: Zm9v
            #     DATADOG_API_KEY: ${{ secrets.DD_TOWNS_LOAD_TESTING_KEY }}
            #     BASE_CHAIN_RPC_URL: ${{ secrets.USEROPS_RPC_URL }}
            #     AA_RPC_URL: ${{ secrets.AA_RPC_URL }}
            #     AA_BUNDLER_URL: ${{ secrets.AA_BUNDLER_URL }}
            #     RIVER_CHAIN_RPC_URL: https://devnet.rpc.river.build
            #     RIVER_ENV: testnet

            #   working-directory: ./clients/web/lib
            #   run: yarn test:userops:random-wallet


            # #### Disabled b/c of flakiness with river membershipChanged event
            # 
            # - name: Run userops tests with verification
            #   timeout-minutes: 15
            #   env:
            #     AA_PAYMASTER_PROXY_URL: http://127.0.0.1:8787
            #     AA_PAYMASTER_PROXY_AUTH_SECRET: Zm9v
            #     DATADOG_API_KEY: ${{ secrets.DD_TOWNS_LOAD_TESTING_KEY }}
            #     BASE_CHAIN_RPC_URL: ${{ secrets.USEROPS_RPC_URL }}
            #     AA_RPC_URL: ${{ secrets.AA_RPC_URL }}
            #     AA_BUNDLER_URL: ${{ secrets.AA_BUNDLER_URL }}
            #     RIVER_CHAIN_RPC_URL: https://devnet.rpc.river.build
            #     RIVER_ENV: testnet

              # working-directory: ./clients/web/lib
              # run: yarn test:userops:privy-wallet

            
            - name: Run @towns/userop package tests with verification (SpaceDapp/base-sepolia)
              timeout-minutes: 15
              env:
                AA_PAYMASTER_PROXY_URL: http://127.0.0.1:8787
                AA_PAYMASTER_PROXY_AUTH_SECRET: Zm9v
                AA_RPC_URL: ${{ secrets.AA_RPC_URL }}
                AA_BUNDLER_URL: ${{ secrets.AA_BUNDLER_URL }}
                RIVER_ENV: testnet

              working-directory: ./clients/web/userops
              run: yarn test:userops:privy-wallet

            # If failed, we send a slack notification
            - name: Slack notification
              if: failure()
              uses: rtCamp/action-slack-notify@v2
              env:
                  SLACK_WEBHOOK: ${{ secrets.SLACK_CI_CHANNEL_WEBHOOK_URL }}
                  SLACK_TITLE: 'Failure'
                  SLACK_USERNAME: 'Userops Tests'
                  SLACK_ICON_EMOJI: ':test_tube:'
                  SLACK_COLOR: '#FF0000'
                  SLACK_MESSAGE: 'Userops Test Failure <@Evan> ${{ vars.GOALIE_SLACK_GROUP_ID }}'
                  SLACK_LINK_NAMES: true
                  
