name: 'Run Userops Tests'
env:
    FOUNDRY_VERSION: nightly

on:
    workflow_dispatch:
    schedule:
        # Once per hour between 8 - 4 PST
        - cron: '0 16-23,0 * * *'

jobs:
    user_ops_tests:
        environment: gamma
        runs-on: ubuntu-latest-8-cores
        timeout-minutes: 240
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Git submodules
              run: git submodule update --init --recursive

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1
              with:
                  version: ${{ env.FOUNDRY_VERSION }}

            - name: Install Forge modules
              run: ./scripts/install-deps.sh

            - uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'yarn'

            - name: Install node dependencies
              run: yarn install --immutable

            - name: Build town types
              run: ./scripts/build-town-types.sh localhost --frozen

            - name: Spin up stackup worker without verification
              working-directory: ./servers/workers/stackup-worker
              # PAYMASTER_ADDRESS is actually the entrypoint address and we need to change the name of this env var
              # https://linear.app/hnt-labs/issue/HNT-4569/change-paymaster-address-to-entrypoint-address-in-paymaster-proxy
              run: yarn dev:local --var PAYMASTER_ADDRESS:0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789 STACKUP_API_TOKEN:${{ secrets.STACKUP_TEST_API_TOKEN }} SKIP_TOWNID_VERIFICATION:true AUTH_SECRET:foo &

            - name: Spin up stackup worker with verification
              working-directory: ./servers/workers/stackup-worker
              # PAYMASTER_ADDRESS is actually the entrypoint address and we need to change the name of this env var
              # https://linear.app/hnt-labs/issue/HNT-4569/change-paymaster-address-to-entrypoint-address-in-paymaster-proxy
              run: PORT=8787 yarn dev:local --var PAYMASTER_ADDRESS:0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789 SKIP_LIMIT_VERIFICATION:true STACKUP_API_TOKEN:${{ secrets.STACKUP_TEST_API_TOKEN }} PRIVY_APP_KEY:${{ secrets.PRIVY_APP_KEY }} PRIVY_APP_ID:clml5fp7s013vmf0fnkabuaiw ALCHEMY_API_KEY:${{ secrets.ALCHEMY_API_KEY }} AUTH_SECRET:foo ENVIRONMENT:test-beta &

            - name: Wait for first stackup worker to be up on 8686
              run: yarn worker:wait:stackup

            - name: Wait for second stackup worker to be up on 8787
              run: PORT=8787 yarn worker:wait:stackup

            - name: Run userops tests without verification
              timeout-minutes: 10
              env:
                AA_PAYMASTER_PROXY_URL: http://127.0.0.1:8686
                CASABLANCA_SERVER_URL: https://river1.nodes.gamma.towns.com
                AA_PAYMASTER_PROXY_AUTH_SECRET: Zm9v
                DATADOG_API_KEY: ${{ secrets.DD_TOWNS_LOAD_TESTING_KEY }}
                ETHERS_NETWORK: ${{ secrets.USEROPS_RPC_URL }}
                AA_RPC_URL: ${{ secrets.AA_RPC_URL }}
                AA_BUNDLER_URL: ${{ secrets.AA_BUNDLER_URL }}

              working-directory: ./clients/web/lib
              run: yarn test:userops:random-wallet

            - name: Run userops tests with verification
              timeout-minutes: 10
              env:
                AA_PAYMASTER_PROXY_URL: http://127.0.0.1:8787
                CASABLANCA_SERVER_URL: https://river1.nodes.gamma.towns.com
                AA_PAYMASTER_PROXY_AUTH_SECRET: Zm9v
                DATADOG_API_KEY: ${{ secrets.DD_TOWNS_LOAD_TESTING_KEY }}
                ETHERS_NETWORK: ${{ secrets.USEROPS_RPC_URL }}
                AA_RPC_URL: ${{ secrets.AA_RPC_URL }}
                AA_BUNDLER_URL: ${{ secrets.AA_BUNDLER_URL }}
                PRIVY_WALLET_PRIVATE_KEY_1: 09892cb15045f5989457e72dd4c7321f29d1dcb93b9f90d78da6fc433852a367
                PRIVY_WALLET_PRIVATE_KEY_2: 757fb31b53bdf75d16ce0342c54047d1a848a66ba3b0d656b883208a88460ee3

              working-directory: ./clients/web/lib
              run: yarn test:userops:privy-wallet

            # If failed, we send a slack notification
            - name: Slack notification
              if: failure()
              uses: rtCamp/action-slack-notify@v2
              env:
                  SLACK_WEBHOOK: ${{ secrets.SLACK_CI_CHANNEL_WEBHOOK_URL }}
                  SLACK_TITLE: 'Failure'
                  SLACK_USERNAME: 'Userops Tests'
                  SLACK_ICON_EMOJI: ':test_tube:'
                  SLACK_COLOR: '#FF0000'
                  SLACK_MESSAGE: 'Userops Test Failure <@Evan>'
