name: 'Run Userops Tests'
env:
    FOUNDRY_VERSION: nightly

on:
    workflow_dispatch: 
    schedule: 
        # Once per hour
        - cron: '0 * * * *'

jobs:
    user_ops_tests:
        environment: test-beta
        runs-on: ubuntu-latest-8-cores
        timeout-minutes: 240
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Git submodules
              run: git submodule update --init --recursive

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1
              with:
                  version: ${{ env.FOUNDRY_VERSION }}

            - name: Install Forge modules
              run: ./scripts/install-deps.sh

            - uses: actions/setup-node@v3
              with:
                  node-version: '18.13.0'
                  cache: 'yarn'

            - name: Install node dependencies
              run: yarn install --immutable

            - name: Build town types
              run: ./scripts/build-town-types.sh localhost --frozen

            - name: Spin up stackup worker
              working-directory: ./servers/workers/stackup-worker
              run: yarn dev:local
              env:
                PAYMASTER_ADDRESS: ${{ env.PAYMASTER_ADDRESS }}
                STACKUP_API_TOKEN: ${{ secrets.STACKUP_API_TOKEN }}
                SKIP_TOWNID_VERIFICATION: true
                PRIVY_APP_KEY: ${{ secrets.PRIVY_APP_KEY }}
                PRIVY_APP_ID: ${{ env.PRIVY_APP_ID }}
                ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
                AUTH_SECRET: foo

            - name: Run userops tests
              env:
                AA_PAYMASTER_PROXY_URL: http://localhost:8686
                CASABLANCA_SERVER_URL: https://river1-test-beta.towns.com
                DATADOG_API_KEY: ${{ secrets.DD_TOWNS_LOAD_TESTING_KEY }}
                ETHERS_NETWORK: ${{ secrets.ETHERS_NETWORK }}
                AA_RPC_URL: ${{ secrets.AA_RPC_URL }}
                AA_BUNDLER_URL: ${{ secrets.AA_BUNDLER_URL }}
                AA_PAYMASTER_PROXY_AUTH_SECRET: Zm9v
                
              working-directory: ./clients/web/lib
              run: yarn test:ci:userops

            # If failed, we send a slack notification
            - name: Slack notification
              if: failure()
              uses: rtCamp/action-slack-notify@v2
              env:
                  SLACK_WEBHOOK: ${{ secrets.SLACK_CI_CHANNEL_WEBHOOK_URL }}
                  SLACK_TITLE: 'Failure'
                  SLACK_USERNAME: 'Userops Tests'
                  SLACK_ICON_EMOJI: ':test_tube:'
                  SLACK_COLOR: '#FF0000'
                  SLACK_MESSAGE: 'Userops Test Failure <@Evan>'
