name: 'Run Wallet Management Tests'
env:
    FOUNDRY_VERSION: nightly

on:
    workflow_dispatch: # Enable manually trigger
    schedule:
        - cron: '0 0 * * *' # Run at 16:00 PST (00:00 UTC next day)
        - cron: '0 7 * * *'  # Run at 23:00 PST (07:00 UTC)
        - cron: '0 16 * * *'  # Run at 08:00 PST (16:00 UTC)
    push:
        branches:
            - wallet

jobs:
    run_wallet_management_tests:
        runs-on: load-testing-runner
        timeout-minutes: 240
        services:
            redis:
                image: redis:latest
                ports:
                    - '6379:6379'

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Git submodules
              run: git submodule update --init --recursive

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1
              with:
                  version: ${{ env.FOUNDRY_VERSION }}

            - name: Install Forge modules
              run: ./scripts/install-deps.sh

            - uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'yarn'

            - name: Install node dependencies
              run: yarn install --immutable

            - name: Build town types
              run: ./scripts/build-town-types.sh localhost --frozen

            - name: Run Wallet Management Tests
              run: yarn test:ci:wallet-management-tests
            # If failed, we send a slack notification
            - name: Slack notification
              if: failure()
              uses: rtCamp/action-slack-notify@v2
              env:
                  SLACK_WEBHOOK: ${{ secrets.SLACK_CI_CHANNEL_WEBHOOK_URL }}
                  SLACK_TITLE: 'Failure'
                  SLACK_USERNAME: 'Load Tests'
                  SLACK_ICON_EMOJI: ':test_tube:'
                  SLACK_COLOR: '#FF0000'
                  SLACK_MESSAGE: 'Wallet Management Failure <@${{ env.TESTS_GOALIE_SLACK_GROUP_ID }}>'
