name: 'Workers_deploy'

on:
    push:
        branches:
            - main
        paths:
            - 'servers/workers/**'
    workflow_dispatch:
        inputs:
            environment:
                description: 'Environment'
                required: true
                default: 'test-beta'
                type: choice
                options:
                    - test-beta

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    deploy:
        name: Deploy CF Workers
        runs-on: ubuntu-latest

        env:
            ENV_NAME: ${{ (github.event_name == 'push' && 'test-beta') || github.event.inputs.environment }}

        permissions:
            contents: write
            packages: write

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Git submodules
              run: git submodule update --init --recursive

            - name: Setup Go
              uses: actions/setup-go@v3
              with:
                  go-version: '1.20'
                  cache: true
                  cache-dependency-path: 'servers/**/go.sum'

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1
              with:
                  version: nightly

            - name: Install Forge modules
              run: ./scripts/install-deps.sh

            - uses: actions/setup-node@v3
              with:
                  node-version: '20'
                  cache: 'yarn'

            - name: Install node dependencies
              run: yarn install --immutable

            - name: Build
              run: yarn workers:build

            - name: Deploy All CF Workers
              run: CLOUDFLARE_API_TOKEN=${{ secrets.CF_API_TOKEN }} ./scripts/deploy-all-workers.sh --environment ${{ env.ENV_NAME }}

            - name: Slack notification
              uses: rtCamp/action-slack-notify@v2
              if: failure()
              env:
                  SLACK_WEBHOOK: ${{ secrets.SLACK_CI_CHANNEL_WEBHOOK_URL }}
                  SLACK_TITLE: 'Failure'
                  SLACK_USERNAME: 'CI'
                  SLACK_ICON_EMOJI: ':boom:'
                  SLACK_COLOR: '#FF0000'
                  SLACK_MESSAGE: 'CF Workers Deploy Failed on ${{ github.repository }}'
