name: 'Build XChain Monitor Docker Image'

on:
    push:
        branches:
            - main
        paths:
            - '.github/workflows/XChain_monitor_docker.yml'
            - '.github/workflows/_build-docker-arch.yml'
            - 'packages/web3/**'
            - 'packages/xchain-monitor/**'
    workflow_dispatch:

env:
    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_CD_WORKFLOW_WEBHOOK_URL }}

jobs:
    build:
        name: Build docker image
        uses: ./.github/workflows/_build-docker-arch.yml
        with:
            architecture: amd64
            platform: linux/amd64
            runner: ubuntu-latest
            ecr_registry_alias: h5v6m2x1
            ecr_repository: xchain-monitor
            dockerfile: ./packages/xchain-monitor/Dockerfile
            cache_scope_prefix: xchain-monitor
            build_args: |
                GIT_SHA=${{ github.sha }}
            extra_tags: ${{ github.sha }}
        secrets: inherit

    # Slack notification on failure
    notify-failure:
        name: Notify on failure
        if: failure()
        needs: [build]
        runs-on: ubuntu-latest
        steps:
            - name: Slack notification
              uses: slackapi/slack-github-action@v1.24.0
              with:
                  payload: |
                      {
                          "step": "Build XChain Monitor Docker Image",
                          "environment": "N/A",
                          "branch": "${{ github.ref }}",
                          "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                          "commit": "${{ github.sha }}",
                          "actor": "${{ github.actor }}"
                      }
